// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package identitysource

import (
    "context"
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i53ac87e8cb3cc9276228f74d38694a208cacb99bb8ceb705eeae99fb88d4d274 "strconv"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    ie2969523f41a2fae7d38164656da4464a9222947e5ea7fbe5cbfbbf94304e5c1 "github.com/topicuskeyhub/sdk-go/models"
    ic5aec28294c6afe4cfe91e8a3597e6eb30f2600e65134e98824ec70e5ca3a854 "github.com/topicuskeyhub/sdk-go/identitysource/item/document/item/row"
)

// ItemDocumentItemRowRequestBuilder builds and executes requests for operations under \identitysource\{identitysource-id}\document\{documentid}\row
type ItemDocumentItemRowRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ItemDocumentItemRowRequestBuilderGetQueryParameters query for imported rows in the imported document. The various query parameters can be used to filter the response.
type ItemDocumentItemRowRequestBuilderGetQueryParameters struct {
    // Request additional information to be returned for every record.
    // Deprecated: This property is deprecated, use AdditionalAsGetAdditionalQueryParameterType instead
    Additional []string `uriparametername:"additional"`
    // Request additional information to be returned for every record.
    AdditionalAsGetAdditionalQueryParameterType []ic5aec28294c6afe4cfe91e8a3597e6eb30f2600e65134e98824ec70e5ca3a854.GetAdditionalQueryParameterType `uriparametername:"additional"`
    // Return all or no records. This can be useful when composing parameters.
    Any []bool `uriparametername:"any"`
    // Only return records that have been created after the given instant.
    CreatedAfter []i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time `uriparametername:"createdAfter"`
    // Only return records that have been created before the given instant.
    CreatedBefore []i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time `uriparametername:"createdBefore"`
    // Only return imported rows for the given imported documents, specified by id. This parameter supports composition with all parameters from the imported document resource.
    Document []int64 `uriparametername:"document"`
    // Filter the results to exclude the given ids.
    Exclude []int64 `uriparametername:"exclude"`
    // Filter the results on the given ids.
    Id []int64 `uriparametername:"id"`
    // Filter imported rows on (part of) the identifier column.
    Identifier []string `uriparametername:"identifier"`
    // Only return imported rows for the given matched accounts, specified by id. This parameter supports composition with all parameters from the account resource.
    MatchedAccount []int64 `uriparametername:"matchedAccount"`
    // Only return records that have been modified since the given instant.
    ModifiedSince []i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time `uriparametername:"modifiedSince"`
    // Filter records on a complex CQL query.
    Q []string `uriparametername:"q"`
    // Sort the items. Use 'asc-<name>' for ascending and 'desc-<name>' for descending order.
    Sort []string `uriparametername:"sort"`
    // Filter imported rows on the given status(es).
    // Deprecated: This property is deprecated, use StatusAsIdentitysourceImportedRowStatus instead
    Status []string `uriparametername:"status"`
    // Filter imported rows on the given status(es).
    StatusAsIdentitysourceImportedRowStatus []ie2969523f41a2fae7d38164656da4464a9222947e5ea7fbe5cbfbbf94304e5c1.IdentitysourceImportedRowStatus `uriparametername:"status"`
}
// ItemDocumentItemRowRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type ItemDocumentItemRowRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *ItemDocumentItemRowRequestBuilderGetQueryParameters
}
// ByRowid gets an item from the github.com/topicuskeyhub/sdk-go.identitysource.item.document.item.row.item collection
// Deprecated: This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.
// returns a *ItemDocumentItemRowWithRowItemRequestBuilder when successful
func (m *ItemDocumentItemRowRequestBuilder) ByRowid(rowid string)(*ItemDocumentItemRowWithRowItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if rowid != "" {
        urlTplParams["rowid"] = rowid
    }
    return NewItemDocumentItemRowWithRowItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// ByRowidInt64 gets an item from the github.com/topicuskeyhub/sdk-go.identitysource.item.document.item.row.item collection
// returns a *ItemDocumentItemRowWithRowItemRequestBuilder when successful
func (m *ItemDocumentItemRowRequestBuilder) ByRowidInt64(rowid int64)(*ItemDocumentItemRowWithRowItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    urlTplParams["rowid"] = i53ac87e8cb3cc9276228f74d38694a208cacb99bb8ceb705eeae99fb88d4d274.FormatInt(rowid, 10)
    return NewItemDocumentItemRowWithRowItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewItemDocumentItemRowRequestBuilderInternal instantiates a new ItemDocumentItemRowRequestBuilder and sets the default values.
func NewItemDocumentItemRowRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemDocumentItemRowRequestBuilder) {
    m := &ItemDocumentItemRowRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/identitysource/{identitysource%2Did}/document/{documentid}/row{?additional*,any*,createdAfter*,createdBefore*,document*,exclude*,id*,identifier*,matchedAccount*,modifiedSince*,q*,sort*,status*}", pathParameters),
    }
    return m
}
// NewItemDocumentItemRowRequestBuilder instantiates a new ItemDocumentItemRowRequestBuilder and sets the default values.
func NewItemDocumentItemRowRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemDocumentItemRowRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewItemDocumentItemRowRequestBuilderInternal(urlParams, requestAdapter)
}
// Get query for imported rows in the imported document. The various query parameters can be used to filter the response.
// returns a IdentitysourceImportedRowLinkableWrapperable when successful
// returns a ErrorReport error when the service returns a 4XX or 5XX status code
func (m *ItemDocumentItemRowRequestBuilder) Get(ctx context.Context, requestConfiguration *ItemDocumentItemRowRequestBuilderGetRequestConfiguration)(ie2969523f41a2fae7d38164656da4464a9222947e5ea7fbe5cbfbbf94304e5c1.IdentitysourceImportedRowLinkableWrapperable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": ie2969523f41a2fae7d38164656da4464a9222947e5ea7fbe5cbfbbf94304e5c1.CreateErrorReportFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, ie2969523f41a2fae7d38164656da4464a9222947e5ea7fbe5cbfbbf94304e5c1.CreateIdentitysourceImportedRowLinkableWrapperFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(ie2969523f41a2fae7d38164656da4464a9222947e5ea7fbe5cbfbbf94304e5c1.IdentitysourceImportedRowLinkableWrapperable), nil
}
// ToGetRequestInformation query for imported rows in the imported document. The various query parameters can be used to filter the response.
// returns a *RequestInformation when successful
func (m *ItemDocumentItemRowRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *ItemDocumentItemRowRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/vnd.topicus.keyhub+json;version=83")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *ItemDocumentItemRowRequestBuilder when successful
func (m *ItemDocumentItemRowRequestBuilder) WithUrl(rawUrl string)(*ItemDocumentItemRowRequestBuilder) {
    return NewItemDocumentItemRowRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
