// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package profile

import (
    "context"
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i53ac87e8cb3cc9276228f74d38694a208cacb99bb8ceb705eeae99fb88d4d274 "strconv"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    ie2969523f41a2fae7d38164656da4464a9222947e5ea7fbe5cbfbbf94304e5c1 "github.com/topicuskeyhub/sdk-go/models"
    i12fcd86d070be643d9bf479dc85d162afea82fcefc778ac6ec5d4614a53453ed "github.com/topicuskeyhub/sdk-go/profile/item/lifecycleaction"
)

// ItemLifecycleactionRequestBuilder builds and executes requests for operations under \profile\{accessprofile-id}\lifecycleaction
type ItemLifecycleactionRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ItemLifecycleactionRequestBuilderGetQueryParameters query for all lifecycle actions of an access profile. The various query parameters can be used to filter the response.
type ItemLifecycleactionRequestBuilderGetQueryParameters struct {
    // Filter lifecycle actions on the given access profiles, specified by id. This parameter supports composition with all parameters from the access profile resource.
    AccessProfile []int64 "uriparametername:\"accessProfile\""
    // Filter lifecycle actions for which the given group is owner, specified by id. This parameter supports composition with all parameters from the group resource.
    AccessProfileOwnedBy []int64 "uriparametername:\"accessProfileOwnedBy\""
    // Request additional information to be returned for every record.
    // Deprecated: This property is deprecated, use AdditionalAsGetAdditionalQueryParameterType instead
    Additional []string "uriparametername:\"additional\""
    // Request additional information to be returned for every record.
    AdditionalAsGetAdditionalQueryParameterType []i12fcd86d070be643d9bf479dc85d162afea82fcefc778ac6ec5d4614a53453ed.GetAdditionalQueryParameterType "uriparametername:\"additional\""
    // Return all or no records. This can be useful when composing parameters.
    Any []bool "uriparametername:\"any\""
    // Only return records that have been created after the given instant.
    CreatedAfter []i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time "uriparametername:\"createdAfter\""
    // Only return records that have been created before the given instant.
    CreatedBefore []i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time "uriparametername:\"createdBefore\""
    // Filter the results to exclude the given ids.
    Exclude []int64 "uriparametername:\"exclude\""
    // Filter the results on the given ids.
    Id []int64 "uriparametername:\"id\""
    // Only return records that have been modified since the given instant.
    ModifiedSince []i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time "uriparametername:\"modifiedSince\""
    // Filter records on a complex CQL query.
    Q []string "uriparametername:\"q\""
    // Sort the items. Use 'asc-<name>' for ascending and 'desc-<name>' for descending order.
    Sort []string "uriparametername:\"sort\""
}
// ItemLifecycleactionRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type ItemLifecycleactionRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *ItemLifecycleactionRequestBuilderGetQueryParameters
}
// ItemLifecycleactionRequestBuilderPostQueryParameters creates one or more new lifecycle actions on an access profile and returns the newly created actions.
type ItemLifecycleactionRequestBuilderPostQueryParameters struct {
    // Request additional information to be returned for every record.
    // Deprecated: This property is deprecated, use AdditionalAsPostAdditionalQueryParameterType instead
    Additional []string "uriparametername:\"additional\""
    // Request additional information to be returned for every record.
    AdditionalAsPostAdditionalQueryParameterType []i12fcd86d070be643d9bf479dc85d162afea82fcefc778ac6ec5d4614a53453ed.PostAdditionalQueryParameterType "uriparametername:\"additional\""
}
// ItemLifecycleactionRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type ItemLifecycleactionRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *ItemLifecycleactionRequestBuilderPostQueryParameters
}
// ByLifecycleactionid gets an item from the github.com/topicuskeyhub/sdk-go.profile.item.lifecycleaction.item collection
// Deprecated: This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.
// returns a *ItemLifecycleactionWithLifecycleactionItemRequestBuilder when successful
func (m *ItemLifecycleactionRequestBuilder) ByLifecycleactionid(lifecycleactionid string)(*ItemLifecycleactionWithLifecycleactionItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if lifecycleactionid != "" {
        urlTplParams["lifecycleactionid"] = lifecycleactionid
    }
    return NewItemLifecycleactionWithLifecycleactionItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// ByLifecycleactionidInt64 gets an item from the github.com/topicuskeyhub/sdk-go.profile.item.lifecycleaction.item collection
// returns a *ItemLifecycleactionWithLifecycleactionItemRequestBuilder when successful
func (m *ItemLifecycleactionRequestBuilder) ByLifecycleactionidInt64(lifecycleactionid int64)(*ItemLifecycleactionWithLifecycleactionItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    urlTplParams["lifecycleactionid"] = i53ac87e8cb3cc9276228f74d38694a208cacb99bb8ceb705eeae99fb88d4d274.FormatInt(lifecycleactionid, 10)
    return NewItemLifecycleactionWithLifecycleactionItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewItemLifecycleactionRequestBuilderInternal instantiates a new ItemLifecycleactionRequestBuilder and sets the default values.
func NewItemLifecycleactionRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemLifecycleactionRequestBuilder) {
    m := &ItemLifecycleactionRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/profile/{accessprofile%2Did}/lifecycleaction{?accessProfile*,accessProfileOwnedBy*,additional*,any*,createdAfter*,createdBefore*,exclude*,id*,modifiedSince*,q*,sort*}", pathParameters),
    }
    return m
}
// NewItemLifecycleactionRequestBuilder instantiates a new ItemLifecycleactionRequestBuilder and sets the default values.
func NewItemLifecycleactionRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemLifecycleactionRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewItemLifecycleactionRequestBuilderInternal(urlParams, requestAdapter)
}
// Get query for all lifecycle actions of an access profile. The various query parameters can be used to filter the response.
// returns a ProfileAccessProfileLifecycleActionLinkableWrapperable when successful
// returns a ErrorReport error when the service returns a 4XX or 5XX status code
func (m *ItemLifecycleactionRequestBuilder) Get(ctx context.Context, requestConfiguration *ItemLifecycleactionRequestBuilderGetRequestConfiguration)(ie2969523f41a2fae7d38164656da4464a9222947e5ea7fbe5cbfbbf94304e5c1.ProfileAccessProfileLifecycleActionLinkableWrapperable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": ie2969523f41a2fae7d38164656da4464a9222947e5ea7fbe5cbfbbf94304e5c1.CreateErrorReportFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, ie2969523f41a2fae7d38164656da4464a9222947e5ea7fbe5cbfbbf94304e5c1.CreateProfileAccessProfileLifecycleActionLinkableWrapperFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(ie2969523f41a2fae7d38164656da4464a9222947e5ea7fbe5cbfbbf94304e5c1.ProfileAccessProfileLifecycleActionLinkableWrapperable), nil
}
// Post creates one or more new lifecycle actions on an access profile and returns the newly created actions.
// returns a ProfileAccessProfileLifecycleActionLinkableWrapperable when successful
// returns a ErrorReport error when the service returns a 4XX or 5XX status code
func (m *ItemLifecycleactionRequestBuilder) Post(ctx context.Context, body ie2969523f41a2fae7d38164656da4464a9222947e5ea7fbe5cbfbbf94304e5c1.ProfileAccessProfileLifecycleActionLinkableWrapperable, requestConfiguration *ItemLifecycleactionRequestBuilderPostRequestConfiguration)(ie2969523f41a2fae7d38164656da4464a9222947e5ea7fbe5cbfbbf94304e5c1.ProfileAccessProfileLifecycleActionLinkableWrapperable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": ie2969523f41a2fae7d38164656da4464a9222947e5ea7fbe5cbfbbf94304e5c1.CreateErrorReportFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, ie2969523f41a2fae7d38164656da4464a9222947e5ea7fbe5cbfbbf94304e5c1.CreateProfileAccessProfileLifecycleActionLinkableWrapperFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(ie2969523f41a2fae7d38164656da4464a9222947e5ea7fbe5cbfbbf94304e5c1.ProfileAccessProfileLifecycleActionLinkableWrapperable), nil
}
// ToGetRequestInformation query for all lifecycle actions of an access profile. The various query parameters can be used to filter the response.
// returns a *RequestInformation when successful
func (m *ItemLifecycleactionRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *ItemLifecycleactionRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/vnd.topicus.keyhub+json;version=87")
    return requestInfo, nil
}
// ToPostRequestInformation creates one or more new lifecycle actions on an access profile and returns the newly created actions.
// returns a *RequestInformation when successful
func (m *ItemLifecycleactionRequestBuilder) ToPostRequestInformation(ctx context.Context, body ie2969523f41a2fae7d38164656da4464a9222947e5ea7fbe5cbfbbf94304e5c1.ProfileAccessProfileLifecycleActionLinkableWrapperable, requestConfiguration *ItemLifecycleactionRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/vnd.topicus.keyhub+json;version=87")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/vnd.topicus.keyhub+json;version=87", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *ItemLifecycleactionRequestBuilder when successful
func (m *ItemLifecycleactionRequestBuilder) WithUrl(rawUrl string)(*ItemLifecycleactionRequestBuilder) {
    return NewItemLifecycleactionRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
