// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package item
type GetAdditionalQueryParameterType int

const (
    ACCOUNTSWITHATTRIBUTES_GETADDITIONALQUERYPARAMETERTYPE GetAdditionalQueryParameterType = iota
    ATTRIBUTERULES_GETADDITIONALQUERYPARAMETERTYPE
    AUDIT_GETADDITIONALQUERYPARAMETERTYPE
    CLIENTS_GETADDITIONALQUERYPARAMETERTYPE
    GROUPS_GETADDITIONALQUERYPARAMETERTYPE
    PROVISIONING_GETADDITIONALQUERYPARAMETERTYPE
)

func (i GetAdditionalQueryParameterType) String() string {
    return []string{"accountsWithAttributes", "attributeRules", "audit", "clients", "groups", "provisioning"}[i]
}
func ParseGetAdditionalQueryParameterType(v string) (any, error) {
    result := ACCOUNTSWITHATTRIBUTES_GETADDITIONALQUERYPARAMETERTYPE
    switch v {
        case "accountsWithAttributes":
            result = ACCOUNTSWITHATTRIBUTES_GETADDITIONALQUERYPARAMETERTYPE
        case "attributeRules":
            result = ATTRIBUTERULES_GETADDITIONALQUERYPARAMETERTYPE
        case "audit":
            result = AUDIT_GETADDITIONALQUERYPARAMETERTYPE
        case "clients":
            result = CLIENTS_GETADDITIONALQUERYPARAMETERTYPE
        case "groups":
            result = GROUPS_GETADDITIONALQUERYPARAMETERTYPE
        case "provisioning":
            result = PROVISIONING_GETADDITIONALQUERYPARAMETERTYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeGetAdditionalQueryParameterType(values []GetAdditionalQueryParameterType) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i GetAdditionalQueryParameterType) isMultiValue() bool {
    return false
}
