package models
type AuditAuditRecordType int

const (
    ACCESS_PROFILE_CREATED_AUDITAUDITRECORDTYPE AuditAuditRecordType = iota
    ACCESS_PROFILE_MODIFIED_AUDITAUDITRECORDTYPE
    ACCESS_PROFILE_REMOVED_AUDITAUDITRECORDTYPE
    ACCOUNT_2FA_DISABLED_AUDITAUDITRECORDTYPE
    ACCOUNT_2FA_ENABLED_AUDITAUDITRECORDTYPE
    ACCOUNT_ACCESS_PROFILE_DEPROVISIONED_AUDITAUDITRECORDTYPE
    ACCOUNT_ACCESS_PROFILE_PROVISIONED_AUDITAUDITRECORDTYPE
    ACCOUNT_ACTIVATION_CODE_USED_AUDITAUDITRECORDTYPE
    ACCOUNT_ADDED_TO_ACCESS_PROFILE_AUDITAUDITRECORDTYPE
    ACCOUNT_ADDED_TO_GROUP_AUDITAUDITRECORDTYPE
    ACCOUNT_ADDED_TO_ORGANIZATIONAL_UNIT_AUDITAUDITRECORDTYPE
    ACCOUNT_CREATED_AUDITAUDITRECORDTYPE
    ACCOUNT_DEPROVISIONED_AUDITAUDITRECORDTYPE
    ACCOUNT_DISABLED_AUDITAUDITRECORDTYPE
    ACCOUNT_ENABLED_AUDITAUDITRECORDTYPE
    ACCOUNT_GROUP_ACTIVATED_AUDITAUDITRECORDTYPE
    ACCOUNT_GROUP_ACTIVATION_REASON_AUDITAUDITRECORDTYPE
    ACCOUNT_GROUP_DEPROVISIONED_AUDITAUDITRECORDTYPE
    ACCOUNT_GROUP_PROVISIONED_AUDITAUDITRECORDTYPE
    ACCOUNT_LOGIN_AUDITAUDITRECORDTYPE
    ACCOUNT_LOGIN_FAILED_AUDITAUDITRECORDTYPE
    ACCOUNT_MODIFIED_FOR_ACCESS_PROFILE_AUDITAUDITRECORDTYPE
    ACCOUNT_MODIFIED_FOR_GROUP_AUDITAUDITRECORDTYPE
    ACCOUNT_PASSWORD_CHANGED_AUDITAUDITRECORDTYPE
    ACCOUNT_PROVISIONED_AUDITAUDITRECORDTYPE
    ACCOUNT_PROVISIONING_DESTROYED_AUDITAUDITRECORDTYPE
    ACCOUNT_PROVISIONING_INITED_AUDITAUDITRECORDTYPE
    ACCOUNT_PROVISIONING_SETUP_AUDITAUDITRECORDTYPE
    ACCOUNT_REMOVED_AUDITAUDITRECORDTYPE
    ACCOUNT_REMOVED_FROM_ACCESS_PROFILE_AUDITAUDITRECORDTYPE
    ACCOUNT_REMOVED_FROM_GROUP_AUDITAUDITRECORDTYPE
    ACCOUNT_REMOVED_FROM_ORGANIZATIONAL_UNIT_AUDITAUDITRECORDTYPE
    ACCOUNT_REREGISTERED_AUDITAUDITRECORDTYPE
    ACCOUNT_SSH_PUBLIC_KEY_MODIFIED_AUDITAUDITRECORDTYPE
    ACCOUNT_TOKEN_SIGNED_AUDITAUDITRECORDTYPE
    ACCOUNT_TOTP_OFFSET_CHANGED_AUDITAUDITRECORDTYPE
    ACCOUNT_VAULT_UNLOCKED_AUDITAUDITRECORDTYPE
    ADD_GROUP_ADMIN_ACCEPTED_AUDITAUDITRECORDTYPE
    ADD_GROUP_ADMIN_DECLINED_AUDITAUDITRECORDTYPE
    ADD_GROUP_ADMIN_REQUESTED_AUDITAUDITRECORDTYPE
    AUDITOR_EXPORT_GENERATED_AUDITAUDITRECORDTYPE
    CERTIFICATE_CREATED_AUDITAUDITRECORDTYPE
    CERTIFICATE_MODIFIED_AUDITAUDITRECORDTYPE
    CERTIFICATE_REMOVED_AUDITAUDITRECORDTYPE
    CLIENT_ADDED_TO_GROUP_AUDITAUDITRECORDTYPE
    CLIENT_CREATED_AUDITAUDITRECORDTYPE
    CLIENT_MODIFIED_AUDITAUDITRECORDTYPE
    CLIENT_MODIFIED_FOR_GROUP_AUDITAUDITRECORDTYPE
    CLIENT_PERMISSION_GRANTED_AUDITAUDITRECORDTYPE
    CLIENT_PERMISSION_REVOKED_AUDITAUDITRECORDTYPE
    CLIENT_REMOVED_AUDITAUDITRECORDTYPE
    CLIENT_REMOVED_FROM_GROUP_AUDITAUDITRECORDTYPE
    CLIENT_SECRET_ROTATED_AUDITAUDITRECORDTYPE
    CREATE_GROUP_ACCEPTED_AUDITAUDITRECORDTYPE
    CREATE_GROUP_DECLINED_AUDITAUDITRECORDTYPE
    CREATE_GROUP_REQUESTED_AUDITAUDITRECORDTYPE
    CREATE_GROUP_ON_SYSTEM_ACCEPTED_AUDITAUDITRECORDTYPE
    CREATE_GROUP_ON_SYSTEM_DECLINED_AUDITAUDITRECORDTYPE
    CREATE_GROUP_ON_SYSTEM_REQUESTED_AUDITAUDITRECORDTYPE
    CREATE_PROVISIONED_NAMESPACE_ACCEPTED_AUDITAUDITRECORDTYPE
    CREATE_PROVISIONED_NAMESPACE_DECLINED_AUDITAUDITRECORDTYPE
    CREATE_PROVISIONED_NAMESPACE_REQUESTED_AUDITAUDITRECORDTYPE
    CREATE_SERVICE_ACCOUNT_ACCEPTED_AUDITAUDITRECORDTYPE
    CREATE_SERVICE_ACCOUNT_DECLINED_AUDITAUDITRECORDTYPE
    CREATE_SERVICE_ACCOUNT_REQUESTED_AUDITAUDITRECORDTYPE
    DIRECTORY_CREATED_AUDITAUDITRECORDTYPE
    DIRECTORY_HELPDESK_MODIFIED_AUDITAUDITRECORDTYPE
    DIRECTORY_MODIFIED_AUDITAUDITRECORDTYPE
    DIRECTORY_REMOVED_AUDITAUDITRECORDTYPE
    DISABLE_2FA_ACCEPTED_AUDITAUDITRECORDTYPE
    DISABLE_2FA_DECLINED_AUDITAUDITRECORDTYPE
    DISABLE_2FA_REQUESTED_AUDITAUDITRECORDTYPE
    ENABLE_PROFILE_ADMINISTRATION_ACCEPTED_AUDITAUDITRECORDTYPE
    ENABLE_PROFILE_ADMINISTRATION_DECLINED_AUDITAUDITRECORDTYPE
    ENABLE_PROFILE_ADMINISTRATION_REQUESTED_AUDITAUDITRECORDTYPE
    ENABLE_TECHNICAL_ADMINISTRATION_ACCEPTED_AUDITAUDITRECORDTYPE
    ENABLE_TECHNICAL_ADMINISTRATION_DECLINED_AUDITAUDITRECORDTYPE
    ENABLE_TECHNICAL_ADMINISTRATION_REQUESTED_AUDITAUDITRECORDTYPE
    EXTENDED_ACCESS_ACCEPTED_AUDITAUDITRECORDTYPE
    EXTENDED_ACCESS_DECLINED_AUDITAUDITRECORDTYPE
    EXTENDED_ACCESS_REQUESTED_AUDITAUDITRECORDTYPE
    GRANT_ACCESS_ACCEPTED_AUDITAUDITRECORDTYPE
    GRANT_ACCESS_DECLINED_AUDITAUDITRECORDTYPE
    GRANT_ACCESS_REQUESTED_AUDITAUDITRECORDTYPE
    GRANT_APPLICATION_ACCEPTED_AUDITAUDITRECORDTYPE
    GRANT_APPLICATION_DECLINED_AUDITAUDITRECORDTYPE
    GRANT_APPLICATION_REQUESTED_AUDITAUDITRECORDTYPE
    GRANT_CLIENT_PERMISSION_ACCEPTED_AUDITAUDITRECORDTYPE
    GRANT_CLIENT_PERMISSION_DECLINED_AUDITAUDITRECORDTYPE
    GRANT_CLIENT_PERMISSION_REQUESTED_AUDITAUDITRECORDTYPE
    GRANT_GROUP_ON_SYSTEM_ACCEPTED_AUDITAUDITRECORDTYPE
    GRANT_GROUP_ON_SYSTEM_DECLINED_AUDITAUDITRECORDTYPE
    GRANT_GROUP_ON_SYSTEM_REQUESTED_AUDITAUDITRECORDTYPE
    GRANT_GROUP_ON_SYSTEM_REQUEST_ACCEPTED_AUDITAUDITRECORDTYPE
    GRANT_GROUP_ON_SYSTEM_REQUEST_DECLINED_AUDITAUDITRECORDTYPE
    GRANT_GROUP_ON_SYSTEM_REQUEST_REQUESTED_AUDITAUDITRECORDTYPE
    GRANT_SERVICE_ACCOUNT_GROUP_ACCEPTED_AUDITAUDITRECORDTYPE
    GRANT_SERVICE_ACCOUNT_GROUP_DECLINED_AUDITAUDITRECORDTYPE
    GRANT_SERVICE_ACCOUNT_GROUP_REQUESTED_AUDITAUDITRECORDTYPE
    GROUP_AUDIT_CREATED_AUDITAUDITRECORDTYPE
    GROUP_AUDIT_REQUESTED_AUDITAUDITRECORDTYPE
    GROUP_AUTHORIZATION_CONNECTED_AUDITAUDITRECORDTYPE
    GROUP_AUTHORIZATION_DISCONNECTED_AUDITAUDITRECORDTYPE
    GROUP_CLASSIFICATION_ASSIGNED_AUDITAUDITRECORDTYPE
    GROUP_CLASSIFICATION_CREATED_AUDITAUDITRECORDTYPE
    GROUP_CLASSIFICATION_MODIFIED_AUDITAUDITRECORDTYPE
    GROUP_CLASSIFICATION_REMOVED_AUDITAUDITRECORDTYPE
    GROUP_CREATED_AUDITAUDITRECORDTYPE
    GROUP_MODIFIED_AUDITAUDITRECORDTYPE
    GROUP_NESTING_CONNECTED_AUDITAUDITRECORDTYPE
    GROUP_NESTING_DISCONNECTED_AUDITAUDITRECORDTYPE
    GROUP_ON_SYSTEM_MODIFIED_AUDITAUDITRECORDTYPE
    GROUP_ON_SYSTEM_DEPROVISIONED_AUDITAUDITRECORDTYPE
    GROUP_ON_SYSTEM_CREATED_AUDITAUDITRECORDTYPE
    GROUP_ON_SYSTEM_PROVISIONED_AUDITAUDITRECORDTYPE
    GROUP_ON_SYSTEM_REMOVED_AUDITAUDITRECORDTYPE
    GROUP_MOVED_AUDITAUDITRECORDTYPE
    GROUP_REMOVED_AUDITAUDITRECORDTYPE
    INTERNAL_ACCOUNT_ACTIVATED_AUDITAUDITRECORDTYPE
    INTERNAL_ACCOUNT_CREATED_AUDITAUDITRECORDTYPE
    INTERNAL_ACCOUNT_MODIFIED_AUDITAUDITRECORDTYPE
    INTERNAL_ACCOUNT_REMOVED_AUDITAUDITRECORDTYPE
    INVALID_SIGNATURE_DETECTED_AUDITAUDITRECORDTYPE
    JOIN_GROUP_ACCEPTED_AUDITAUDITRECORDTYPE
    JOIN_GROUP_DECLINED_AUDITAUDITRECORDTYPE
    JOIN_GROUP_REQUESTED_AUDITAUDITRECORDTYPE
    JOIN_VAULT_ACCEPTED_AUDITAUDITRECORDTYPE
    JOIN_VAULT_DECLINED_AUDITAUDITRECORDTYPE
    JOIN_VAULT_REQUESTED_AUDITAUDITRECORDTYPE
    LICENSE_KEY_UPLOADED_AUDITAUDITRECORDTYPE
    MOVE_GROUPS_ACCEPTED_AUDITAUDITRECORDTYPE
    MOVE_GROUPS_DECLINED_AUDITAUDITRECORDTYPE
    MOVE_GROUPS_REQUESTED_AUDITAUDITRECORDTYPE
    ORGANIZATIONAL_UNIT_CREATED_AUDITAUDITRECORDTYPE
    ORGANIZATIONAL_UNIT_MODIFIED_AUDITAUDITRECORDTYPE
    ORGANIZATIONAL_UNIT_REMOVED_AUDITAUDITRECORDTYPE
    PROVISIONED_SYSTEM_ADDED_TO_ACCESS_PROFILE_AUDITAUDITRECORDTYPE
    PROVISIONED_SYSTEM_ADDED_TO_GROUP_AUDITAUDITRECORDTYPE
    PROVISIONED_SYSTEM_CREATED_AUDITAUDITRECORDTYPE
    PROVISIONED_SYSTEM_MODIFIED_AUDITAUDITRECORDTYPE
    PROVISIONED_SYSTEM_MODIFIED_FOR_GROUP_AUDITAUDITRECORDTYPE
    PROVISIONED_SYSTEM_REMOVED_AUDITAUDITRECORDTYPE
    PROVISIONED_SYSTEM_REMOVED_FROM_ACCESS_PROFILE_AUDITAUDITRECORDTYPE
    PROVISIONED_SYSTEM_REMOVED_FROM_GROUP_AUDITAUDITRECORDTYPE
    PROVISIONED_SYSTEM_UNKNOWN_ACCOUNT_DESTROYED_AUDITAUDITRECORDTYPE
    REMOVE_GROUP_ACCEPTED_AUDITAUDITRECORDTYPE
    REMOVE_GROUP_DECLINED_AUDITAUDITRECORDTYPE
    REMOVE_GROUP_REQUESTED_AUDITAUDITRECORDTYPE
    REMOVE_ORGANIZATIONAL_UNIT_ACCEPTED_AUDITAUDITRECORDTYPE
    REMOVE_ORGANIZATIONAL_UNIT_DECLINED_AUDITAUDITRECORDTYPE
    REMOVE_ORGANIZATIONAL_UNIT_REQUESTED_AUDITAUDITRECORDTYPE
    REMOVE_PROVISIONED_SYSTEM_ACCEPTED_AUDITAUDITRECORDTYPE
    REMOVE_PROVISIONED_SYSTEM_DECLINED_AUDITAUDITRECORDTYPE
    REMOVE_PROVISIONED_SYSTEM_REQUESTED_AUDITAUDITRECORDTYPE
    RESET_PASSWORD_ACCEPTED_AUDITAUDITRECORDTYPE
    RESET_PASSWORD_DECLINED_AUDITAUDITRECORDTYPE
    RESET_PASSWORD_FINISHED_AUDITAUDITRECORDTYPE
    RESET_PASSWORD_REQUESTED_AUDITAUDITRECORDTYPE
    REVIEW_AUDIT_ACCEPTED_AUDITAUDITRECORDTYPE
    REVIEW_AUDIT_DECLINED_AUDITAUDITRECORDTYPE
    REVIEW_AUDIT_REQUESTED_AUDITAUDITRECORDTYPE
    REVOKE_ADMIN_ACCEPTED_AUDITAUDITRECORDTYPE
    REVOKE_ADMIN_DECLINED_AUDITAUDITRECORDTYPE
    REVOKE_ADMIN_REQUESTED_AUDITAUDITRECORDTYPE
    SERVICE_ACCOUNT_ADDED_TO_GROUP_AUDITAUDITRECORDTYPE
    SERVICE_ACCOUNT_CREATED_AUDITAUDITRECORDTYPE
    SERVICE_ACCOUNT_GROUP_DEPROVISIONED_AUDITAUDITRECORDTYPE
    SERVICE_ACCOUNT_GROUP_PROVISIONED_AUDITAUDITRECORDTYPE
    SERVICE_ACCOUNT_MODIFIED_AUDITAUDITRECORDTYPE
    SERVICE_ACCOUNT_PASSWORD_ROTATED_AUDITAUDITRECORDTYPE
    SERVICE_ACCOUNT_PROVISIONING_DESTROYED_AUDITAUDITRECORDTYPE
    SERVICE_ACCOUNT_PROVISIONING_INITED_AUDITAUDITRECORDTYPE
    SERVICE_ACCOUNT_REMOVED_AUDITAUDITRECORDTYPE
    SERVICE_ACCOUNT_REMOVED_FROM_GROUP_AUDITAUDITRECORDTYPE
    SETTING_MODIFIED_AUDITAUDITRECORDTYPE
    SETUP_AUTHORIZING_GROUP_CONNECT_ACCEPTED_AUDITAUDITRECORDTYPE
    SETUP_AUTHORIZING_GROUP_CONNECT_DECLINED_AUDITAUDITRECORDTYPE
    SETUP_AUTHORIZING_GROUP_CONNECT_REQUESTED_AUDITAUDITRECORDTYPE
    SETUP_AUTHORIZING_GROUP_DISCONNECT_ACCEPTED_AUDITAUDITRECORDTYPE
    SETUP_AUTHORIZING_GROUP_DISCONNECT_DECLINED_AUDITAUDITRECORDTYPE
    SETUP_AUTHORIZING_GROUP_DISCONNECT_REQUESTED_AUDITAUDITRECORDTYPE
    SETUP_NESTED_GROUP_CONNECT_ACCEPTED_AUDITAUDITRECORDTYPE
    SETUP_NESTED_GROUP_CONNECT_DECLINED_AUDITAUDITRECORDTYPE
    SETUP_NESTED_GROUP_CONNECT_REQUESTED_AUDITAUDITRECORDTYPE
    SETUP_NESTED_GROUP_DISCONNECT_ACCEPTED_AUDITAUDITRECORDTYPE
    SETUP_NESTED_GROUP_DISCONNECT_DECLINED_AUDITAUDITRECORDTYPE
    SETUP_NESTED_GROUP_DISCONNECT_REQUESTED_AUDITAUDITRECORDTYPE
    TRANSFER_ACCESS_PROFILE_OWNERSHIP_ACCEPTED_AUDITAUDITRECORDTYPE
    TRANSFER_ACCESS_PROFILE_OWNERSHIP_DECLINED_AUDITAUDITRECORDTYPE
    TRANSFER_ACCESS_PROFILE_OWNERSHIP_REQUESTED_AUDITAUDITRECORDTYPE
    TRANSFER_APPLICATION_ADMINISTRATION_ACCEPTED_AUDITAUDITRECORDTYPE
    TRANSFER_APPLICATION_ADMINISTRATION_DECLINED_AUDITAUDITRECORDTYPE
    TRANSFER_APPLICATION_ADMINISTRATION_REQUESTED_AUDITAUDITRECORDTYPE
    TRANSFER_APPLICATION_OWNERSHIP_ACCEPTED_AUDITAUDITRECORDTYPE
    TRANSFER_APPLICATION_OWNERSHIP_DECLINED_AUDITAUDITRECORDTYPE
    TRANSFER_APPLICATION_OWNERSHIP_REQUESTED_AUDITAUDITRECORDTYPE
    TRANSFER_GROUP_ON_SYSTEM_OWNERSHIP_ACCEPTED_AUDITAUDITRECORDTYPE
    TRANSFER_GROUP_ON_SYSTEM_OWNERSHIP_DECLINED_AUDITAUDITRECORDTYPE
    TRANSFER_GROUP_ON_SYSTEM_OWNERSHIP_REQUESTED_AUDITAUDITRECORDTYPE
    TRANSFER_ORGANIZATIONAL_UNIT_OWNERSHIP_ACCEPTED_AUDITAUDITRECORDTYPE
    TRANSFER_ORGANIZATIONAL_UNIT_OWNERSHIP_DECLINED_AUDITAUDITRECORDTYPE
    TRANSFER_ORGANIZATIONAL_UNIT_OWNERSHIP_REQUESTED_AUDITAUDITRECORDTYPE
    TRANSFER_PROVISIONED_SYSTEM_ADMINISTRATION_ACCEPTED_AUDITAUDITRECORDTYPE
    TRANSFER_PROVISIONED_SYSTEM_ADMINISTRATION_DECLINED_AUDITAUDITRECORDTYPE
    TRANSFER_PROVISIONED_SYSTEM_ADMINISTRATION_REQUESTED_AUDITAUDITRECORDTYPE
    TRANSFER_PROVISIONED_SYSTEM_CONTENT_ADMINISTRATION_ACCEPTED_AUDITAUDITRECORDTYPE
    TRANSFER_PROVISIONED_SYSTEM_CONTENT_ADMINISTRATION_DECLINED_AUDITAUDITRECORDTYPE
    TRANSFER_PROVISIONED_SYSTEM_CONTENT_ADMINISTRATION_REQUESTED_AUDITAUDITRECORDTYPE
    TRANSFER_PROVISIONED_SYSTEM_OWNERSHIP_ACCEPTED_AUDITAUDITRECORDTYPE
    TRANSFER_PROVISIONED_SYSTEM_OWNERSHIP_DECLINED_AUDITAUDITRECORDTYPE
    TRANSFER_PROVISIONED_SYSTEM_OWNERSHIP_REQUESTED_AUDITAUDITRECORDTYPE
    TRANSFER_SERVICE_ACCOUNT_ADMINISTRATION_ACCEPTED_AUDITAUDITRECORDTYPE
    TRANSFER_SERVICE_ACCOUNT_ADMINISTRATION_DECLINED_AUDITAUDITRECORDTYPE
    TRANSFER_SERVICE_ACCOUNT_ADMINISTRATION_REQUESTED_AUDITAUDITRECORDTYPE
    UPDATE_GROUP_MEMBERSHIP_ACCEPTED_AUDITAUDITRECORDTYPE
    UPDATE_GROUP_MEMBERSHIP_DECLINED_AUDITAUDITRECORDTYPE
    UPDATE_GROUP_MEMBERSHIP_REQUESTED_AUDITAUDITRECORDTYPE
    VAULT_ACCESS_RESTORED_AUDITAUDITRECORDTYPE
    VAULT_EXPORTED_AUDITAUDITRECORDTYPE
    VAULT_PERSONAL_RESET_AUDITAUDITRECORDTYPE
    VAULT_PERSONAL_SETUP_AUDITAUDITRECORDTYPE
    VAULT_RECORD_CREATED_AUDITAUDITRECORDTYPE
    VAULT_RECORD_MODIFIED_AUDITAUDITRECORDTYPE
    VAULT_RECORD_MOVED_COPIED_SHARED_AUDITAUDITRECORDTYPE
    VAULT_RECORD_READ_AUDITAUDITRECORDTYPE
    VAULT_RECORD_REMOVED_AUDITAUDITRECORDTYPE
    VAULT_RECOVERED_AUDITAUDITRECORDTYPE
    VERIFY_INTERNAL_ACCOUNT_ACCEPTED_AUDITAUDITRECORDTYPE
    VERIFY_INTERNAL_ACCOUNT_DECLINED_AUDITAUDITRECORDTYPE
    VERIFY_INTERNAL_ACCOUNT_REQUESTED_AUDITAUDITRECORDTYPE
    WEBHOOK_CREATED_AUDITAUDITRECORDTYPE
    WEBHOOK_MODIFIED_AUDITAUDITRECORDTYPE
    WEBHOOK_REMOVED_AUDITAUDITRECORDTYPE
)

func (i AuditAuditRecordType) String() string {
    return []string{"ACCESS_PROFILE_CREATED", "ACCESS_PROFILE_MODIFIED", "ACCESS_PROFILE_REMOVED", "ACCOUNT_2FA_DISABLED", "ACCOUNT_2FA_ENABLED", "ACCOUNT_ACCESS_PROFILE_DEPROVISIONED", "ACCOUNT_ACCESS_PROFILE_PROVISIONED", "ACCOUNT_ACTIVATION_CODE_USED", "ACCOUNT_ADDED_TO_ACCESS_PROFILE", "ACCOUNT_ADDED_TO_GROUP", "ACCOUNT_ADDED_TO_ORGANIZATIONAL_UNIT", "ACCOUNT_CREATED", "ACCOUNT_DEPROVISIONED", "ACCOUNT_DISABLED", "ACCOUNT_ENABLED", "ACCOUNT_GROUP_ACTIVATED", "ACCOUNT_GROUP_ACTIVATION_REASON", "ACCOUNT_GROUP_DEPROVISIONED", "ACCOUNT_GROUP_PROVISIONED", "ACCOUNT_LOGIN", "ACCOUNT_LOGIN_FAILED", "ACCOUNT_MODIFIED_FOR_ACCESS_PROFILE", "ACCOUNT_MODIFIED_FOR_GROUP", "ACCOUNT_PASSWORD_CHANGED", "ACCOUNT_PROVISIONED", "ACCOUNT_PROVISIONING_DESTROYED", "ACCOUNT_PROVISIONING_INITED", "ACCOUNT_PROVISIONING_SETUP", "ACCOUNT_REMOVED", "ACCOUNT_REMOVED_FROM_ACCESS_PROFILE", "ACCOUNT_REMOVED_FROM_GROUP", "ACCOUNT_REMOVED_FROM_ORGANIZATIONAL_UNIT", "ACCOUNT_REREGISTERED", "ACCOUNT_SSH_PUBLIC_KEY_MODIFIED", "ACCOUNT_TOKEN_SIGNED", "ACCOUNT_TOTP_OFFSET_CHANGED", "ACCOUNT_VAULT_UNLOCKED", "ADD_GROUP_ADMIN_ACCEPTED", "ADD_GROUP_ADMIN_DECLINED", "ADD_GROUP_ADMIN_REQUESTED", "AUDITOR_EXPORT_GENERATED", "CERTIFICATE_CREATED", "CERTIFICATE_MODIFIED", "CERTIFICATE_REMOVED", "CLIENT_ADDED_TO_GROUP", "CLIENT_CREATED", "CLIENT_MODIFIED", "CLIENT_MODIFIED_FOR_GROUP", "CLIENT_PERMISSION_GRANTED", "CLIENT_PERMISSION_REVOKED", "CLIENT_REMOVED", "CLIENT_REMOVED_FROM_GROUP", "CLIENT_SECRET_ROTATED", "CREATE_GROUP_ACCEPTED", "CREATE_GROUP_DECLINED", "CREATE_GROUP_REQUESTED", "CREATE_GROUP_ON_SYSTEM_ACCEPTED", "CREATE_GROUP_ON_SYSTEM_DECLINED", "CREATE_GROUP_ON_SYSTEM_REQUESTED", "CREATE_PROVISIONED_NAMESPACE_ACCEPTED", "CREATE_PROVISIONED_NAMESPACE_DECLINED", "CREATE_PROVISIONED_NAMESPACE_REQUESTED", "CREATE_SERVICE_ACCOUNT_ACCEPTED", "CREATE_SERVICE_ACCOUNT_DECLINED", "CREATE_SERVICE_ACCOUNT_REQUESTED", "DIRECTORY_CREATED", "DIRECTORY_HELPDESK_MODIFIED", "DIRECTORY_MODIFIED", "DIRECTORY_REMOVED", "DISABLE_2FA_ACCEPTED", "DISABLE_2FA_DECLINED", "DISABLE_2FA_REQUESTED", "ENABLE_PROFILE_ADMINISTRATION_ACCEPTED", "ENABLE_PROFILE_ADMINISTRATION_DECLINED", "ENABLE_PROFILE_ADMINISTRATION_REQUESTED", "ENABLE_TECHNICAL_ADMINISTRATION_ACCEPTED", "ENABLE_TECHNICAL_ADMINISTRATION_DECLINED", "ENABLE_TECHNICAL_ADMINISTRATION_REQUESTED", "EXTENDED_ACCESS_ACCEPTED", "EXTENDED_ACCESS_DECLINED", "EXTENDED_ACCESS_REQUESTED", "GRANT_ACCESS_ACCEPTED", "GRANT_ACCESS_DECLINED", "GRANT_ACCESS_REQUESTED", "GRANT_APPLICATION_ACCEPTED", "GRANT_APPLICATION_DECLINED", "GRANT_APPLICATION_REQUESTED", "GRANT_CLIENT_PERMISSION_ACCEPTED", "GRANT_CLIENT_PERMISSION_DECLINED", "GRANT_CLIENT_PERMISSION_REQUESTED", "GRANT_GROUP_ON_SYSTEM_ACCEPTED", "GRANT_GROUP_ON_SYSTEM_DECLINED", "GRANT_GROUP_ON_SYSTEM_REQUESTED", "GRANT_GROUP_ON_SYSTEM_REQUEST_ACCEPTED", "GRANT_GROUP_ON_SYSTEM_REQUEST_DECLINED", "GRANT_GROUP_ON_SYSTEM_REQUEST_REQUESTED", "GRANT_SERVICE_ACCOUNT_GROUP_ACCEPTED", "GRANT_SERVICE_ACCOUNT_GROUP_DECLINED", "GRANT_SERVICE_ACCOUNT_GROUP_REQUESTED", "GROUP_AUDIT_CREATED", "GROUP_AUDIT_REQUESTED", "GROUP_AUTHORIZATION_CONNECTED", "GROUP_AUTHORIZATION_DISCONNECTED", "GROUP_CLASSIFICATION_ASSIGNED", "GROUP_CLASSIFICATION_CREATED", "GROUP_CLASSIFICATION_MODIFIED", "GROUP_CLASSIFICATION_REMOVED", "GROUP_CREATED", "GROUP_MODIFIED", "GROUP_NESTING_CONNECTED", "GROUP_NESTING_DISCONNECTED", "GROUP_ON_SYSTEM_MODIFIED", "GROUP_ON_SYSTEM_DEPROVISIONED", "GROUP_ON_SYSTEM_CREATED", "GROUP_ON_SYSTEM_PROVISIONED", "GROUP_ON_SYSTEM_REMOVED", "GROUP_MOVED", "GROUP_REMOVED", "INTERNAL_ACCOUNT_ACTIVATED", "INTERNAL_ACCOUNT_CREATED", "INTERNAL_ACCOUNT_MODIFIED", "INTERNAL_ACCOUNT_REMOVED", "INVALID_SIGNATURE_DETECTED", "JOIN_GROUP_ACCEPTED", "JOIN_GROUP_DECLINED", "JOIN_GROUP_REQUESTED", "JOIN_VAULT_ACCEPTED", "JOIN_VAULT_DECLINED", "JOIN_VAULT_REQUESTED", "LICENSE_KEY_UPLOADED", "MOVE_GROUPS_ACCEPTED", "MOVE_GROUPS_DECLINED", "MOVE_GROUPS_REQUESTED", "ORGANIZATIONAL_UNIT_CREATED", "ORGANIZATIONAL_UNIT_MODIFIED", "ORGANIZATIONAL_UNIT_REMOVED", "PROVISIONED_SYSTEM_ADDED_TO_ACCESS_PROFILE", "PROVISIONED_SYSTEM_ADDED_TO_GROUP", "PROVISIONED_SYSTEM_CREATED", "PROVISIONED_SYSTEM_MODIFIED", "PROVISIONED_SYSTEM_MODIFIED_FOR_GROUP", "PROVISIONED_SYSTEM_REMOVED", "PROVISIONED_SYSTEM_REMOVED_FROM_ACCESS_PROFILE", "PROVISIONED_SYSTEM_REMOVED_FROM_GROUP", "PROVISIONED_SYSTEM_UNKNOWN_ACCOUNT_DESTROYED", "REMOVE_GROUP_ACCEPTED", "REMOVE_GROUP_DECLINED", "REMOVE_GROUP_REQUESTED", "REMOVE_ORGANIZATIONAL_UNIT_ACCEPTED", "REMOVE_ORGANIZATIONAL_UNIT_DECLINED", "REMOVE_ORGANIZATIONAL_UNIT_REQUESTED", "REMOVE_PROVISIONED_SYSTEM_ACCEPTED", "REMOVE_PROVISIONED_SYSTEM_DECLINED", "REMOVE_PROVISIONED_SYSTEM_REQUESTED", "RESET_PASSWORD_ACCEPTED", "RESET_PASSWORD_DECLINED", "RESET_PASSWORD_FINISHED", "RESET_PASSWORD_REQUESTED", "REVIEW_AUDIT_ACCEPTED", "REVIEW_AUDIT_DECLINED", "REVIEW_AUDIT_REQUESTED", "REVOKE_ADMIN_ACCEPTED", "REVOKE_ADMIN_DECLINED", "REVOKE_ADMIN_REQUESTED", "SERVICE_ACCOUNT_ADDED_TO_GROUP", "SERVICE_ACCOUNT_CREATED", "SERVICE_ACCOUNT_GROUP_DEPROVISIONED", "SERVICE_ACCOUNT_GROUP_PROVISIONED", "SERVICE_ACCOUNT_MODIFIED", "SERVICE_ACCOUNT_PASSWORD_ROTATED", "SERVICE_ACCOUNT_PROVISIONING_DESTROYED", "SERVICE_ACCOUNT_PROVISIONING_INITED", "SERVICE_ACCOUNT_REMOVED", "SERVICE_ACCOUNT_REMOVED_FROM_GROUP", "SETTING_MODIFIED", "SETUP_AUTHORIZING_GROUP_CONNECT_ACCEPTED", "SETUP_AUTHORIZING_GROUP_CONNECT_DECLINED", "SETUP_AUTHORIZING_GROUP_CONNECT_REQUESTED", "SETUP_AUTHORIZING_GROUP_DISCONNECT_ACCEPTED", "SETUP_AUTHORIZING_GROUP_DISCONNECT_DECLINED", "SETUP_AUTHORIZING_GROUP_DISCONNECT_REQUESTED", "SETUP_NESTED_GROUP_CONNECT_ACCEPTED", "SETUP_NESTED_GROUP_CONNECT_DECLINED", "SETUP_NESTED_GROUP_CONNECT_REQUESTED", "SETUP_NESTED_GROUP_DISCONNECT_ACCEPTED", "SETUP_NESTED_GROUP_DISCONNECT_DECLINED", "SETUP_NESTED_GROUP_DISCONNECT_REQUESTED", "TRANSFER_ACCESS_PROFILE_OWNERSHIP_ACCEPTED", "TRANSFER_ACCESS_PROFILE_OWNERSHIP_DECLINED", "TRANSFER_ACCESS_PROFILE_OWNERSHIP_REQUESTED", "TRANSFER_APPLICATION_ADMINISTRATION_ACCEPTED", "TRANSFER_APPLICATION_ADMINISTRATION_DECLINED", "TRANSFER_APPLICATION_ADMINISTRATION_REQUESTED", "TRANSFER_APPLICATION_OWNERSHIP_ACCEPTED", "TRANSFER_APPLICATION_OWNERSHIP_DECLINED", "TRANSFER_APPLICATION_OWNERSHIP_REQUESTED", "TRANSFER_GROUP_ON_SYSTEM_OWNERSHIP_ACCEPTED", "TRANSFER_GROUP_ON_SYSTEM_OWNERSHIP_DECLINED", "TRANSFER_GROUP_ON_SYSTEM_OWNERSHIP_REQUESTED", "TRANSFER_ORGANIZATIONAL_UNIT_OWNERSHIP_ACCEPTED", "TRANSFER_ORGANIZATIONAL_UNIT_OWNERSHIP_DECLINED", "TRANSFER_ORGANIZATIONAL_UNIT_OWNERSHIP_REQUESTED", "TRANSFER_PROVISIONED_SYSTEM_ADMINISTRATION_ACCEPTED", "TRANSFER_PROVISIONED_SYSTEM_ADMINISTRATION_DECLINED", "TRANSFER_PROVISIONED_SYSTEM_ADMINISTRATION_REQUESTED", "TRANSFER_PROVISIONED_SYSTEM_CONTENT_ADMINISTRATION_ACCEPTED", "TRANSFER_PROVISIONED_SYSTEM_CONTENT_ADMINISTRATION_DECLINED", "TRANSFER_PROVISIONED_SYSTEM_CONTENT_ADMINISTRATION_REQUESTED", "TRANSFER_PROVISIONED_SYSTEM_OWNERSHIP_ACCEPTED", "TRANSFER_PROVISIONED_SYSTEM_OWNERSHIP_DECLINED", "TRANSFER_PROVISIONED_SYSTEM_OWNERSHIP_REQUESTED", "TRANSFER_SERVICE_ACCOUNT_ADMINISTRATION_ACCEPTED", "TRANSFER_SERVICE_ACCOUNT_ADMINISTRATION_DECLINED", "TRANSFER_SERVICE_ACCOUNT_ADMINISTRATION_REQUESTED", "UPDATE_GROUP_MEMBERSHIP_ACCEPTED", "UPDATE_GROUP_MEMBERSHIP_DECLINED", "UPDATE_GROUP_MEMBERSHIP_REQUESTED", "VAULT_ACCESS_RESTORED", "VAULT_EXPORTED", "VAULT_PERSONAL_RESET", "VAULT_PERSONAL_SETUP", "VAULT_RECORD_CREATED", "VAULT_RECORD_MODIFIED", "VAULT_RECORD_MOVED_COPIED_SHARED", "VAULT_RECORD_READ", "VAULT_RECORD_REMOVED", "VAULT_RECOVERED", "VERIFY_INTERNAL_ACCOUNT_ACCEPTED", "VERIFY_INTERNAL_ACCOUNT_DECLINED", "VERIFY_INTERNAL_ACCOUNT_REQUESTED", "WEBHOOK_CREATED", "WEBHOOK_MODIFIED", "WEBHOOK_REMOVED"}[i]
}
func ParseAuditAuditRecordType(v string) (any, error) {
    result := ACCESS_PROFILE_CREATED_AUDITAUDITRECORDTYPE
    switch v {
        case "ACCESS_PROFILE_CREATED":
            result = ACCESS_PROFILE_CREATED_AUDITAUDITRECORDTYPE
        case "ACCESS_PROFILE_MODIFIED":
            result = ACCESS_PROFILE_MODIFIED_AUDITAUDITRECORDTYPE
        case "ACCESS_PROFILE_REMOVED":
            result = ACCESS_PROFILE_REMOVED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_2FA_DISABLED":
            result = ACCOUNT_2FA_DISABLED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_2FA_ENABLED":
            result = ACCOUNT_2FA_ENABLED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_ACCESS_PROFILE_DEPROVISIONED":
            result = ACCOUNT_ACCESS_PROFILE_DEPROVISIONED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_ACCESS_PROFILE_PROVISIONED":
            result = ACCOUNT_ACCESS_PROFILE_PROVISIONED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_ACTIVATION_CODE_USED":
            result = ACCOUNT_ACTIVATION_CODE_USED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_ADDED_TO_ACCESS_PROFILE":
            result = ACCOUNT_ADDED_TO_ACCESS_PROFILE_AUDITAUDITRECORDTYPE
        case "ACCOUNT_ADDED_TO_GROUP":
            result = ACCOUNT_ADDED_TO_GROUP_AUDITAUDITRECORDTYPE
        case "ACCOUNT_ADDED_TO_ORGANIZATIONAL_UNIT":
            result = ACCOUNT_ADDED_TO_ORGANIZATIONAL_UNIT_AUDITAUDITRECORDTYPE
        case "ACCOUNT_CREATED":
            result = ACCOUNT_CREATED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_DEPROVISIONED":
            result = ACCOUNT_DEPROVISIONED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_DISABLED":
            result = ACCOUNT_DISABLED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_ENABLED":
            result = ACCOUNT_ENABLED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_GROUP_ACTIVATED":
            result = ACCOUNT_GROUP_ACTIVATED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_GROUP_ACTIVATION_REASON":
            result = ACCOUNT_GROUP_ACTIVATION_REASON_AUDITAUDITRECORDTYPE
        case "ACCOUNT_GROUP_DEPROVISIONED":
            result = ACCOUNT_GROUP_DEPROVISIONED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_GROUP_PROVISIONED":
            result = ACCOUNT_GROUP_PROVISIONED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_LOGIN":
            result = ACCOUNT_LOGIN_AUDITAUDITRECORDTYPE
        case "ACCOUNT_LOGIN_FAILED":
            result = ACCOUNT_LOGIN_FAILED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_MODIFIED_FOR_ACCESS_PROFILE":
            result = ACCOUNT_MODIFIED_FOR_ACCESS_PROFILE_AUDITAUDITRECORDTYPE
        case "ACCOUNT_MODIFIED_FOR_GROUP":
            result = ACCOUNT_MODIFIED_FOR_GROUP_AUDITAUDITRECORDTYPE
        case "ACCOUNT_PASSWORD_CHANGED":
            result = ACCOUNT_PASSWORD_CHANGED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_PROVISIONED":
            result = ACCOUNT_PROVISIONED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_PROVISIONING_DESTROYED":
            result = ACCOUNT_PROVISIONING_DESTROYED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_PROVISIONING_INITED":
            result = ACCOUNT_PROVISIONING_INITED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_PROVISIONING_SETUP":
            result = ACCOUNT_PROVISIONING_SETUP_AUDITAUDITRECORDTYPE
        case "ACCOUNT_REMOVED":
            result = ACCOUNT_REMOVED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_REMOVED_FROM_ACCESS_PROFILE":
            result = ACCOUNT_REMOVED_FROM_ACCESS_PROFILE_AUDITAUDITRECORDTYPE
        case "ACCOUNT_REMOVED_FROM_GROUP":
            result = ACCOUNT_REMOVED_FROM_GROUP_AUDITAUDITRECORDTYPE
        case "ACCOUNT_REMOVED_FROM_ORGANIZATIONAL_UNIT":
            result = ACCOUNT_REMOVED_FROM_ORGANIZATIONAL_UNIT_AUDITAUDITRECORDTYPE
        case "ACCOUNT_REREGISTERED":
            result = ACCOUNT_REREGISTERED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_SSH_PUBLIC_KEY_MODIFIED":
            result = ACCOUNT_SSH_PUBLIC_KEY_MODIFIED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_TOKEN_SIGNED":
            result = ACCOUNT_TOKEN_SIGNED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_TOTP_OFFSET_CHANGED":
            result = ACCOUNT_TOTP_OFFSET_CHANGED_AUDITAUDITRECORDTYPE
        case "ACCOUNT_VAULT_UNLOCKED":
            result = ACCOUNT_VAULT_UNLOCKED_AUDITAUDITRECORDTYPE
        case "ADD_GROUP_ADMIN_ACCEPTED":
            result = ADD_GROUP_ADMIN_ACCEPTED_AUDITAUDITRECORDTYPE
        case "ADD_GROUP_ADMIN_DECLINED":
            result = ADD_GROUP_ADMIN_DECLINED_AUDITAUDITRECORDTYPE
        case "ADD_GROUP_ADMIN_REQUESTED":
            result = ADD_GROUP_ADMIN_REQUESTED_AUDITAUDITRECORDTYPE
        case "AUDITOR_EXPORT_GENERATED":
            result = AUDITOR_EXPORT_GENERATED_AUDITAUDITRECORDTYPE
        case "CERTIFICATE_CREATED":
            result = CERTIFICATE_CREATED_AUDITAUDITRECORDTYPE
        case "CERTIFICATE_MODIFIED":
            result = CERTIFICATE_MODIFIED_AUDITAUDITRECORDTYPE
        case "CERTIFICATE_REMOVED":
            result = CERTIFICATE_REMOVED_AUDITAUDITRECORDTYPE
        case "CLIENT_ADDED_TO_GROUP":
            result = CLIENT_ADDED_TO_GROUP_AUDITAUDITRECORDTYPE
        case "CLIENT_CREATED":
            result = CLIENT_CREATED_AUDITAUDITRECORDTYPE
        case "CLIENT_MODIFIED":
            result = CLIENT_MODIFIED_AUDITAUDITRECORDTYPE
        case "CLIENT_MODIFIED_FOR_GROUP":
            result = CLIENT_MODIFIED_FOR_GROUP_AUDITAUDITRECORDTYPE
        case "CLIENT_PERMISSION_GRANTED":
            result = CLIENT_PERMISSION_GRANTED_AUDITAUDITRECORDTYPE
        case "CLIENT_PERMISSION_REVOKED":
            result = CLIENT_PERMISSION_REVOKED_AUDITAUDITRECORDTYPE
        case "CLIENT_REMOVED":
            result = CLIENT_REMOVED_AUDITAUDITRECORDTYPE
        case "CLIENT_REMOVED_FROM_GROUP":
            result = CLIENT_REMOVED_FROM_GROUP_AUDITAUDITRECORDTYPE
        case "CLIENT_SECRET_ROTATED":
            result = CLIENT_SECRET_ROTATED_AUDITAUDITRECORDTYPE
        case "CREATE_GROUP_ACCEPTED":
            result = CREATE_GROUP_ACCEPTED_AUDITAUDITRECORDTYPE
        case "CREATE_GROUP_DECLINED":
            result = CREATE_GROUP_DECLINED_AUDITAUDITRECORDTYPE
        case "CREATE_GROUP_REQUESTED":
            result = CREATE_GROUP_REQUESTED_AUDITAUDITRECORDTYPE
        case "CREATE_GROUP_ON_SYSTEM_ACCEPTED":
            result = CREATE_GROUP_ON_SYSTEM_ACCEPTED_AUDITAUDITRECORDTYPE
        case "CREATE_GROUP_ON_SYSTEM_DECLINED":
            result = CREATE_GROUP_ON_SYSTEM_DECLINED_AUDITAUDITRECORDTYPE
        case "CREATE_GROUP_ON_SYSTEM_REQUESTED":
            result = CREATE_GROUP_ON_SYSTEM_REQUESTED_AUDITAUDITRECORDTYPE
        case "CREATE_PROVISIONED_NAMESPACE_ACCEPTED":
            result = CREATE_PROVISIONED_NAMESPACE_ACCEPTED_AUDITAUDITRECORDTYPE
        case "CREATE_PROVISIONED_NAMESPACE_DECLINED":
            result = CREATE_PROVISIONED_NAMESPACE_DECLINED_AUDITAUDITRECORDTYPE
        case "CREATE_PROVISIONED_NAMESPACE_REQUESTED":
            result = CREATE_PROVISIONED_NAMESPACE_REQUESTED_AUDITAUDITRECORDTYPE
        case "CREATE_SERVICE_ACCOUNT_ACCEPTED":
            result = CREATE_SERVICE_ACCOUNT_ACCEPTED_AUDITAUDITRECORDTYPE
        case "CREATE_SERVICE_ACCOUNT_DECLINED":
            result = CREATE_SERVICE_ACCOUNT_DECLINED_AUDITAUDITRECORDTYPE
        case "CREATE_SERVICE_ACCOUNT_REQUESTED":
            result = CREATE_SERVICE_ACCOUNT_REQUESTED_AUDITAUDITRECORDTYPE
        case "DIRECTORY_CREATED":
            result = DIRECTORY_CREATED_AUDITAUDITRECORDTYPE
        case "DIRECTORY_HELPDESK_MODIFIED":
            result = DIRECTORY_HELPDESK_MODIFIED_AUDITAUDITRECORDTYPE
        case "DIRECTORY_MODIFIED":
            result = DIRECTORY_MODIFIED_AUDITAUDITRECORDTYPE
        case "DIRECTORY_REMOVED":
            result = DIRECTORY_REMOVED_AUDITAUDITRECORDTYPE
        case "DISABLE_2FA_ACCEPTED":
            result = DISABLE_2FA_ACCEPTED_AUDITAUDITRECORDTYPE
        case "DISABLE_2FA_DECLINED":
            result = DISABLE_2FA_DECLINED_AUDITAUDITRECORDTYPE
        case "DISABLE_2FA_REQUESTED":
            result = DISABLE_2FA_REQUESTED_AUDITAUDITRECORDTYPE
        case "ENABLE_PROFILE_ADMINISTRATION_ACCEPTED":
            result = ENABLE_PROFILE_ADMINISTRATION_ACCEPTED_AUDITAUDITRECORDTYPE
        case "ENABLE_PROFILE_ADMINISTRATION_DECLINED":
            result = ENABLE_PROFILE_ADMINISTRATION_DECLINED_AUDITAUDITRECORDTYPE
        case "ENABLE_PROFILE_ADMINISTRATION_REQUESTED":
            result = ENABLE_PROFILE_ADMINISTRATION_REQUESTED_AUDITAUDITRECORDTYPE
        case "ENABLE_TECHNICAL_ADMINISTRATION_ACCEPTED":
            result = ENABLE_TECHNICAL_ADMINISTRATION_ACCEPTED_AUDITAUDITRECORDTYPE
        case "ENABLE_TECHNICAL_ADMINISTRATION_DECLINED":
            result = ENABLE_TECHNICAL_ADMINISTRATION_DECLINED_AUDITAUDITRECORDTYPE
        case "ENABLE_TECHNICAL_ADMINISTRATION_REQUESTED":
            result = ENABLE_TECHNICAL_ADMINISTRATION_REQUESTED_AUDITAUDITRECORDTYPE
        case "EXTENDED_ACCESS_ACCEPTED":
            result = EXTENDED_ACCESS_ACCEPTED_AUDITAUDITRECORDTYPE
        case "EXTENDED_ACCESS_DECLINED":
            result = EXTENDED_ACCESS_DECLINED_AUDITAUDITRECORDTYPE
        case "EXTENDED_ACCESS_REQUESTED":
            result = EXTENDED_ACCESS_REQUESTED_AUDITAUDITRECORDTYPE
        case "GRANT_ACCESS_ACCEPTED":
            result = GRANT_ACCESS_ACCEPTED_AUDITAUDITRECORDTYPE
        case "GRANT_ACCESS_DECLINED":
            result = GRANT_ACCESS_DECLINED_AUDITAUDITRECORDTYPE
        case "GRANT_ACCESS_REQUESTED":
            result = GRANT_ACCESS_REQUESTED_AUDITAUDITRECORDTYPE
        case "GRANT_APPLICATION_ACCEPTED":
            result = GRANT_APPLICATION_ACCEPTED_AUDITAUDITRECORDTYPE
        case "GRANT_APPLICATION_DECLINED":
            result = GRANT_APPLICATION_DECLINED_AUDITAUDITRECORDTYPE
        case "GRANT_APPLICATION_REQUESTED":
            result = GRANT_APPLICATION_REQUESTED_AUDITAUDITRECORDTYPE
        case "GRANT_CLIENT_PERMISSION_ACCEPTED":
            result = GRANT_CLIENT_PERMISSION_ACCEPTED_AUDITAUDITRECORDTYPE
        case "GRANT_CLIENT_PERMISSION_DECLINED":
            result = GRANT_CLIENT_PERMISSION_DECLINED_AUDITAUDITRECORDTYPE
        case "GRANT_CLIENT_PERMISSION_REQUESTED":
            result = GRANT_CLIENT_PERMISSION_REQUESTED_AUDITAUDITRECORDTYPE
        case "GRANT_GROUP_ON_SYSTEM_ACCEPTED":
            result = GRANT_GROUP_ON_SYSTEM_ACCEPTED_AUDITAUDITRECORDTYPE
        case "GRANT_GROUP_ON_SYSTEM_DECLINED":
            result = GRANT_GROUP_ON_SYSTEM_DECLINED_AUDITAUDITRECORDTYPE
        case "GRANT_GROUP_ON_SYSTEM_REQUESTED":
            result = GRANT_GROUP_ON_SYSTEM_REQUESTED_AUDITAUDITRECORDTYPE
        case "GRANT_GROUP_ON_SYSTEM_REQUEST_ACCEPTED":
            result = GRANT_GROUP_ON_SYSTEM_REQUEST_ACCEPTED_AUDITAUDITRECORDTYPE
        case "GRANT_GROUP_ON_SYSTEM_REQUEST_DECLINED":
            result = GRANT_GROUP_ON_SYSTEM_REQUEST_DECLINED_AUDITAUDITRECORDTYPE
        case "GRANT_GROUP_ON_SYSTEM_REQUEST_REQUESTED":
            result = GRANT_GROUP_ON_SYSTEM_REQUEST_REQUESTED_AUDITAUDITRECORDTYPE
        case "GRANT_SERVICE_ACCOUNT_GROUP_ACCEPTED":
            result = GRANT_SERVICE_ACCOUNT_GROUP_ACCEPTED_AUDITAUDITRECORDTYPE
        case "GRANT_SERVICE_ACCOUNT_GROUP_DECLINED":
            result = GRANT_SERVICE_ACCOUNT_GROUP_DECLINED_AUDITAUDITRECORDTYPE
        case "GRANT_SERVICE_ACCOUNT_GROUP_REQUESTED":
            result = GRANT_SERVICE_ACCOUNT_GROUP_REQUESTED_AUDITAUDITRECORDTYPE
        case "GROUP_AUDIT_CREATED":
            result = GROUP_AUDIT_CREATED_AUDITAUDITRECORDTYPE
        case "GROUP_AUDIT_REQUESTED":
            result = GROUP_AUDIT_REQUESTED_AUDITAUDITRECORDTYPE
        case "GROUP_AUTHORIZATION_CONNECTED":
            result = GROUP_AUTHORIZATION_CONNECTED_AUDITAUDITRECORDTYPE
        case "GROUP_AUTHORIZATION_DISCONNECTED":
            result = GROUP_AUTHORIZATION_DISCONNECTED_AUDITAUDITRECORDTYPE
        case "GROUP_CLASSIFICATION_ASSIGNED":
            result = GROUP_CLASSIFICATION_ASSIGNED_AUDITAUDITRECORDTYPE
        case "GROUP_CLASSIFICATION_CREATED":
            result = GROUP_CLASSIFICATION_CREATED_AUDITAUDITRECORDTYPE
        case "GROUP_CLASSIFICATION_MODIFIED":
            result = GROUP_CLASSIFICATION_MODIFIED_AUDITAUDITRECORDTYPE
        case "GROUP_CLASSIFICATION_REMOVED":
            result = GROUP_CLASSIFICATION_REMOVED_AUDITAUDITRECORDTYPE
        case "GROUP_CREATED":
            result = GROUP_CREATED_AUDITAUDITRECORDTYPE
        case "GROUP_MODIFIED":
            result = GROUP_MODIFIED_AUDITAUDITRECORDTYPE
        case "GROUP_NESTING_CONNECTED":
            result = GROUP_NESTING_CONNECTED_AUDITAUDITRECORDTYPE
        case "GROUP_NESTING_DISCONNECTED":
            result = GROUP_NESTING_DISCONNECTED_AUDITAUDITRECORDTYPE
        case "GROUP_ON_SYSTEM_MODIFIED":
            result = GROUP_ON_SYSTEM_MODIFIED_AUDITAUDITRECORDTYPE
        case "GROUP_ON_SYSTEM_DEPROVISIONED":
            result = GROUP_ON_SYSTEM_DEPROVISIONED_AUDITAUDITRECORDTYPE
        case "GROUP_ON_SYSTEM_CREATED":
            result = GROUP_ON_SYSTEM_CREATED_AUDITAUDITRECORDTYPE
        case "GROUP_ON_SYSTEM_PROVISIONED":
            result = GROUP_ON_SYSTEM_PROVISIONED_AUDITAUDITRECORDTYPE
        case "GROUP_ON_SYSTEM_REMOVED":
            result = GROUP_ON_SYSTEM_REMOVED_AUDITAUDITRECORDTYPE
        case "GROUP_MOVED":
            result = GROUP_MOVED_AUDITAUDITRECORDTYPE
        case "GROUP_REMOVED":
            result = GROUP_REMOVED_AUDITAUDITRECORDTYPE
        case "INTERNAL_ACCOUNT_ACTIVATED":
            result = INTERNAL_ACCOUNT_ACTIVATED_AUDITAUDITRECORDTYPE
        case "INTERNAL_ACCOUNT_CREATED":
            result = INTERNAL_ACCOUNT_CREATED_AUDITAUDITRECORDTYPE
        case "INTERNAL_ACCOUNT_MODIFIED":
            result = INTERNAL_ACCOUNT_MODIFIED_AUDITAUDITRECORDTYPE
        case "INTERNAL_ACCOUNT_REMOVED":
            result = INTERNAL_ACCOUNT_REMOVED_AUDITAUDITRECORDTYPE
        case "INVALID_SIGNATURE_DETECTED":
            result = INVALID_SIGNATURE_DETECTED_AUDITAUDITRECORDTYPE
        case "JOIN_GROUP_ACCEPTED":
            result = JOIN_GROUP_ACCEPTED_AUDITAUDITRECORDTYPE
        case "JOIN_GROUP_DECLINED":
            result = JOIN_GROUP_DECLINED_AUDITAUDITRECORDTYPE
        case "JOIN_GROUP_REQUESTED":
            result = JOIN_GROUP_REQUESTED_AUDITAUDITRECORDTYPE
        case "JOIN_VAULT_ACCEPTED":
            result = JOIN_VAULT_ACCEPTED_AUDITAUDITRECORDTYPE
        case "JOIN_VAULT_DECLINED":
            result = JOIN_VAULT_DECLINED_AUDITAUDITRECORDTYPE
        case "JOIN_VAULT_REQUESTED":
            result = JOIN_VAULT_REQUESTED_AUDITAUDITRECORDTYPE
        case "LICENSE_KEY_UPLOADED":
            result = LICENSE_KEY_UPLOADED_AUDITAUDITRECORDTYPE
        case "MOVE_GROUPS_ACCEPTED":
            result = MOVE_GROUPS_ACCEPTED_AUDITAUDITRECORDTYPE
        case "MOVE_GROUPS_DECLINED":
            result = MOVE_GROUPS_DECLINED_AUDITAUDITRECORDTYPE
        case "MOVE_GROUPS_REQUESTED":
            result = MOVE_GROUPS_REQUESTED_AUDITAUDITRECORDTYPE
        case "ORGANIZATIONAL_UNIT_CREATED":
            result = ORGANIZATIONAL_UNIT_CREATED_AUDITAUDITRECORDTYPE
        case "ORGANIZATIONAL_UNIT_MODIFIED":
            result = ORGANIZATIONAL_UNIT_MODIFIED_AUDITAUDITRECORDTYPE
        case "ORGANIZATIONAL_UNIT_REMOVED":
            result = ORGANIZATIONAL_UNIT_REMOVED_AUDITAUDITRECORDTYPE
        case "PROVISIONED_SYSTEM_ADDED_TO_ACCESS_PROFILE":
            result = PROVISIONED_SYSTEM_ADDED_TO_ACCESS_PROFILE_AUDITAUDITRECORDTYPE
        case "PROVISIONED_SYSTEM_ADDED_TO_GROUP":
            result = PROVISIONED_SYSTEM_ADDED_TO_GROUP_AUDITAUDITRECORDTYPE
        case "PROVISIONED_SYSTEM_CREATED":
            result = PROVISIONED_SYSTEM_CREATED_AUDITAUDITRECORDTYPE
        case "PROVISIONED_SYSTEM_MODIFIED":
            result = PROVISIONED_SYSTEM_MODIFIED_AUDITAUDITRECORDTYPE
        case "PROVISIONED_SYSTEM_MODIFIED_FOR_GROUP":
            result = PROVISIONED_SYSTEM_MODIFIED_FOR_GROUP_AUDITAUDITRECORDTYPE
        case "PROVISIONED_SYSTEM_REMOVED":
            result = PROVISIONED_SYSTEM_REMOVED_AUDITAUDITRECORDTYPE
        case "PROVISIONED_SYSTEM_REMOVED_FROM_ACCESS_PROFILE":
            result = PROVISIONED_SYSTEM_REMOVED_FROM_ACCESS_PROFILE_AUDITAUDITRECORDTYPE
        case "PROVISIONED_SYSTEM_REMOVED_FROM_GROUP":
            result = PROVISIONED_SYSTEM_REMOVED_FROM_GROUP_AUDITAUDITRECORDTYPE
        case "PROVISIONED_SYSTEM_UNKNOWN_ACCOUNT_DESTROYED":
            result = PROVISIONED_SYSTEM_UNKNOWN_ACCOUNT_DESTROYED_AUDITAUDITRECORDTYPE
        case "REMOVE_GROUP_ACCEPTED":
            result = REMOVE_GROUP_ACCEPTED_AUDITAUDITRECORDTYPE
        case "REMOVE_GROUP_DECLINED":
            result = REMOVE_GROUP_DECLINED_AUDITAUDITRECORDTYPE
        case "REMOVE_GROUP_REQUESTED":
            result = REMOVE_GROUP_REQUESTED_AUDITAUDITRECORDTYPE
        case "REMOVE_ORGANIZATIONAL_UNIT_ACCEPTED":
            result = REMOVE_ORGANIZATIONAL_UNIT_ACCEPTED_AUDITAUDITRECORDTYPE
        case "REMOVE_ORGANIZATIONAL_UNIT_DECLINED":
            result = REMOVE_ORGANIZATIONAL_UNIT_DECLINED_AUDITAUDITRECORDTYPE
        case "REMOVE_ORGANIZATIONAL_UNIT_REQUESTED":
            result = REMOVE_ORGANIZATIONAL_UNIT_REQUESTED_AUDITAUDITRECORDTYPE
        case "REMOVE_PROVISIONED_SYSTEM_ACCEPTED":
            result = REMOVE_PROVISIONED_SYSTEM_ACCEPTED_AUDITAUDITRECORDTYPE
        case "REMOVE_PROVISIONED_SYSTEM_DECLINED":
            result = REMOVE_PROVISIONED_SYSTEM_DECLINED_AUDITAUDITRECORDTYPE
        case "REMOVE_PROVISIONED_SYSTEM_REQUESTED":
            result = REMOVE_PROVISIONED_SYSTEM_REQUESTED_AUDITAUDITRECORDTYPE
        case "RESET_PASSWORD_ACCEPTED":
            result = RESET_PASSWORD_ACCEPTED_AUDITAUDITRECORDTYPE
        case "RESET_PASSWORD_DECLINED":
            result = RESET_PASSWORD_DECLINED_AUDITAUDITRECORDTYPE
        case "RESET_PASSWORD_FINISHED":
            result = RESET_PASSWORD_FINISHED_AUDITAUDITRECORDTYPE
        case "RESET_PASSWORD_REQUESTED":
            result = RESET_PASSWORD_REQUESTED_AUDITAUDITRECORDTYPE
        case "REVIEW_AUDIT_ACCEPTED":
            result = REVIEW_AUDIT_ACCEPTED_AUDITAUDITRECORDTYPE
        case "REVIEW_AUDIT_DECLINED":
            result = REVIEW_AUDIT_DECLINED_AUDITAUDITRECORDTYPE
        case "REVIEW_AUDIT_REQUESTED":
            result = REVIEW_AUDIT_REQUESTED_AUDITAUDITRECORDTYPE
        case "REVOKE_ADMIN_ACCEPTED":
            result = REVOKE_ADMIN_ACCEPTED_AUDITAUDITRECORDTYPE
        case "REVOKE_ADMIN_DECLINED":
            result = REVOKE_ADMIN_DECLINED_AUDITAUDITRECORDTYPE
        case "REVOKE_ADMIN_REQUESTED":
            result = REVOKE_ADMIN_REQUESTED_AUDITAUDITRECORDTYPE
        case "SERVICE_ACCOUNT_ADDED_TO_GROUP":
            result = SERVICE_ACCOUNT_ADDED_TO_GROUP_AUDITAUDITRECORDTYPE
        case "SERVICE_ACCOUNT_CREATED":
            result = SERVICE_ACCOUNT_CREATED_AUDITAUDITRECORDTYPE
        case "SERVICE_ACCOUNT_GROUP_DEPROVISIONED":
            result = SERVICE_ACCOUNT_GROUP_DEPROVISIONED_AUDITAUDITRECORDTYPE
        case "SERVICE_ACCOUNT_GROUP_PROVISIONED":
            result = SERVICE_ACCOUNT_GROUP_PROVISIONED_AUDITAUDITRECORDTYPE
        case "SERVICE_ACCOUNT_MODIFIED":
            result = SERVICE_ACCOUNT_MODIFIED_AUDITAUDITRECORDTYPE
        case "SERVICE_ACCOUNT_PASSWORD_ROTATED":
            result = SERVICE_ACCOUNT_PASSWORD_ROTATED_AUDITAUDITRECORDTYPE
        case "SERVICE_ACCOUNT_PROVISIONING_DESTROYED":
            result = SERVICE_ACCOUNT_PROVISIONING_DESTROYED_AUDITAUDITRECORDTYPE
        case "SERVICE_ACCOUNT_PROVISIONING_INITED":
            result = SERVICE_ACCOUNT_PROVISIONING_INITED_AUDITAUDITRECORDTYPE
        case "SERVICE_ACCOUNT_REMOVED":
            result = SERVICE_ACCOUNT_REMOVED_AUDITAUDITRECORDTYPE
        case "SERVICE_ACCOUNT_REMOVED_FROM_GROUP":
            result = SERVICE_ACCOUNT_REMOVED_FROM_GROUP_AUDITAUDITRECORDTYPE
        case "SETTING_MODIFIED":
            result = SETTING_MODIFIED_AUDITAUDITRECORDTYPE
        case "SETUP_AUTHORIZING_GROUP_CONNECT_ACCEPTED":
            result = SETUP_AUTHORIZING_GROUP_CONNECT_ACCEPTED_AUDITAUDITRECORDTYPE
        case "SETUP_AUTHORIZING_GROUP_CONNECT_DECLINED":
            result = SETUP_AUTHORIZING_GROUP_CONNECT_DECLINED_AUDITAUDITRECORDTYPE
        case "SETUP_AUTHORIZING_GROUP_CONNECT_REQUESTED":
            result = SETUP_AUTHORIZING_GROUP_CONNECT_REQUESTED_AUDITAUDITRECORDTYPE
        case "SETUP_AUTHORIZING_GROUP_DISCONNECT_ACCEPTED":
            result = SETUP_AUTHORIZING_GROUP_DISCONNECT_ACCEPTED_AUDITAUDITRECORDTYPE
        case "SETUP_AUTHORIZING_GROUP_DISCONNECT_DECLINED":
            result = SETUP_AUTHORIZING_GROUP_DISCONNECT_DECLINED_AUDITAUDITRECORDTYPE
        case "SETUP_AUTHORIZING_GROUP_DISCONNECT_REQUESTED":
            result = SETUP_AUTHORIZING_GROUP_DISCONNECT_REQUESTED_AUDITAUDITRECORDTYPE
        case "SETUP_NESTED_GROUP_CONNECT_ACCEPTED":
            result = SETUP_NESTED_GROUP_CONNECT_ACCEPTED_AUDITAUDITRECORDTYPE
        case "SETUP_NESTED_GROUP_CONNECT_DECLINED":
            result = SETUP_NESTED_GROUP_CONNECT_DECLINED_AUDITAUDITRECORDTYPE
        case "SETUP_NESTED_GROUP_CONNECT_REQUESTED":
            result = SETUP_NESTED_GROUP_CONNECT_REQUESTED_AUDITAUDITRECORDTYPE
        case "SETUP_NESTED_GROUP_DISCONNECT_ACCEPTED":
            result = SETUP_NESTED_GROUP_DISCONNECT_ACCEPTED_AUDITAUDITRECORDTYPE
        case "SETUP_NESTED_GROUP_DISCONNECT_DECLINED":
            result = SETUP_NESTED_GROUP_DISCONNECT_DECLINED_AUDITAUDITRECORDTYPE
        case "SETUP_NESTED_GROUP_DISCONNECT_REQUESTED":
            result = SETUP_NESTED_GROUP_DISCONNECT_REQUESTED_AUDITAUDITRECORDTYPE
        case "TRANSFER_ACCESS_PROFILE_OWNERSHIP_ACCEPTED":
            result = TRANSFER_ACCESS_PROFILE_OWNERSHIP_ACCEPTED_AUDITAUDITRECORDTYPE
        case "TRANSFER_ACCESS_PROFILE_OWNERSHIP_DECLINED":
            result = TRANSFER_ACCESS_PROFILE_OWNERSHIP_DECLINED_AUDITAUDITRECORDTYPE
        case "TRANSFER_ACCESS_PROFILE_OWNERSHIP_REQUESTED":
            result = TRANSFER_ACCESS_PROFILE_OWNERSHIP_REQUESTED_AUDITAUDITRECORDTYPE
        case "TRANSFER_APPLICATION_ADMINISTRATION_ACCEPTED":
            result = TRANSFER_APPLICATION_ADMINISTRATION_ACCEPTED_AUDITAUDITRECORDTYPE
        case "TRANSFER_APPLICATION_ADMINISTRATION_DECLINED":
            result = TRANSFER_APPLICATION_ADMINISTRATION_DECLINED_AUDITAUDITRECORDTYPE
        case "TRANSFER_APPLICATION_ADMINISTRATION_REQUESTED":
            result = TRANSFER_APPLICATION_ADMINISTRATION_REQUESTED_AUDITAUDITRECORDTYPE
        case "TRANSFER_APPLICATION_OWNERSHIP_ACCEPTED":
            result = TRANSFER_APPLICATION_OWNERSHIP_ACCEPTED_AUDITAUDITRECORDTYPE
        case "TRANSFER_APPLICATION_OWNERSHIP_DECLINED":
            result = TRANSFER_APPLICATION_OWNERSHIP_DECLINED_AUDITAUDITRECORDTYPE
        case "TRANSFER_APPLICATION_OWNERSHIP_REQUESTED":
            result = TRANSFER_APPLICATION_OWNERSHIP_REQUESTED_AUDITAUDITRECORDTYPE
        case "TRANSFER_GROUP_ON_SYSTEM_OWNERSHIP_ACCEPTED":
            result = TRANSFER_GROUP_ON_SYSTEM_OWNERSHIP_ACCEPTED_AUDITAUDITRECORDTYPE
        case "TRANSFER_GROUP_ON_SYSTEM_OWNERSHIP_DECLINED":
            result = TRANSFER_GROUP_ON_SYSTEM_OWNERSHIP_DECLINED_AUDITAUDITRECORDTYPE
        case "TRANSFER_GROUP_ON_SYSTEM_OWNERSHIP_REQUESTED":
            result = TRANSFER_GROUP_ON_SYSTEM_OWNERSHIP_REQUESTED_AUDITAUDITRECORDTYPE
        case "TRANSFER_ORGANIZATIONAL_UNIT_OWNERSHIP_ACCEPTED":
            result = TRANSFER_ORGANIZATIONAL_UNIT_OWNERSHIP_ACCEPTED_AUDITAUDITRECORDTYPE
        case "TRANSFER_ORGANIZATIONAL_UNIT_OWNERSHIP_DECLINED":
            result = TRANSFER_ORGANIZATIONAL_UNIT_OWNERSHIP_DECLINED_AUDITAUDITRECORDTYPE
        case "TRANSFER_ORGANIZATIONAL_UNIT_OWNERSHIP_REQUESTED":
            result = TRANSFER_ORGANIZATIONAL_UNIT_OWNERSHIP_REQUESTED_AUDITAUDITRECORDTYPE
        case "TRANSFER_PROVISIONED_SYSTEM_ADMINISTRATION_ACCEPTED":
            result = TRANSFER_PROVISIONED_SYSTEM_ADMINISTRATION_ACCEPTED_AUDITAUDITRECORDTYPE
        case "TRANSFER_PROVISIONED_SYSTEM_ADMINISTRATION_DECLINED":
            result = TRANSFER_PROVISIONED_SYSTEM_ADMINISTRATION_DECLINED_AUDITAUDITRECORDTYPE
        case "TRANSFER_PROVISIONED_SYSTEM_ADMINISTRATION_REQUESTED":
            result = TRANSFER_PROVISIONED_SYSTEM_ADMINISTRATION_REQUESTED_AUDITAUDITRECORDTYPE
        case "TRANSFER_PROVISIONED_SYSTEM_CONTENT_ADMINISTRATION_ACCEPTED":
            result = TRANSFER_PROVISIONED_SYSTEM_CONTENT_ADMINISTRATION_ACCEPTED_AUDITAUDITRECORDTYPE
        case "TRANSFER_PROVISIONED_SYSTEM_CONTENT_ADMINISTRATION_DECLINED":
            result = TRANSFER_PROVISIONED_SYSTEM_CONTENT_ADMINISTRATION_DECLINED_AUDITAUDITRECORDTYPE
        case "TRANSFER_PROVISIONED_SYSTEM_CONTENT_ADMINISTRATION_REQUESTED":
            result = TRANSFER_PROVISIONED_SYSTEM_CONTENT_ADMINISTRATION_REQUESTED_AUDITAUDITRECORDTYPE
        case "TRANSFER_PROVISIONED_SYSTEM_OWNERSHIP_ACCEPTED":
            result = TRANSFER_PROVISIONED_SYSTEM_OWNERSHIP_ACCEPTED_AUDITAUDITRECORDTYPE
        case "TRANSFER_PROVISIONED_SYSTEM_OWNERSHIP_DECLINED":
            result = TRANSFER_PROVISIONED_SYSTEM_OWNERSHIP_DECLINED_AUDITAUDITRECORDTYPE
        case "TRANSFER_PROVISIONED_SYSTEM_OWNERSHIP_REQUESTED":
            result = TRANSFER_PROVISIONED_SYSTEM_OWNERSHIP_REQUESTED_AUDITAUDITRECORDTYPE
        case "TRANSFER_SERVICE_ACCOUNT_ADMINISTRATION_ACCEPTED":
            result = TRANSFER_SERVICE_ACCOUNT_ADMINISTRATION_ACCEPTED_AUDITAUDITRECORDTYPE
        case "TRANSFER_SERVICE_ACCOUNT_ADMINISTRATION_DECLINED":
            result = TRANSFER_SERVICE_ACCOUNT_ADMINISTRATION_DECLINED_AUDITAUDITRECORDTYPE
        case "TRANSFER_SERVICE_ACCOUNT_ADMINISTRATION_REQUESTED":
            result = TRANSFER_SERVICE_ACCOUNT_ADMINISTRATION_REQUESTED_AUDITAUDITRECORDTYPE
        case "UPDATE_GROUP_MEMBERSHIP_ACCEPTED":
            result = UPDATE_GROUP_MEMBERSHIP_ACCEPTED_AUDITAUDITRECORDTYPE
        case "UPDATE_GROUP_MEMBERSHIP_DECLINED":
            result = UPDATE_GROUP_MEMBERSHIP_DECLINED_AUDITAUDITRECORDTYPE
        case "UPDATE_GROUP_MEMBERSHIP_REQUESTED":
            result = UPDATE_GROUP_MEMBERSHIP_REQUESTED_AUDITAUDITRECORDTYPE
        case "VAULT_ACCESS_RESTORED":
            result = VAULT_ACCESS_RESTORED_AUDITAUDITRECORDTYPE
        case "VAULT_EXPORTED":
            result = VAULT_EXPORTED_AUDITAUDITRECORDTYPE
        case "VAULT_PERSONAL_RESET":
            result = VAULT_PERSONAL_RESET_AUDITAUDITRECORDTYPE
        case "VAULT_PERSONAL_SETUP":
            result = VAULT_PERSONAL_SETUP_AUDITAUDITRECORDTYPE
        case "VAULT_RECORD_CREATED":
            result = VAULT_RECORD_CREATED_AUDITAUDITRECORDTYPE
        case "VAULT_RECORD_MODIFIED":
            result = VAULT_RECORD_MODIFIED_AUDITAUDITRECORDTYPE
        case "VAULT_RECORD_MOVED_COPIED_SHARED":
            result = VAULT_RECORD_MOVED_COPIED_SHARED_AUDITAUDITRECORDTYPE
        case "VAULT_RECORD_READ":
            result = VAULT_RECORD_READ_AUDITAUDITRECORDTYPE
        case "VAULT_RECORD_REMOVED":
            result = VAULT_RECORD_REMOVED_AUDITAUDITRECORDTYPE
        case "VAULT_RECOVERED":
            result = VAULT_RECOVERED_AUDITAUDITRECORDTYPE
        case "VERIFY_INTERNAL_ACCOUNT_ACCEPTED":
            result = VERIFY_INTERNAL_ACCOUNT_ACCEPTED_AUDITAUDITRECORDTYPE
        case "VERIFY_INTERNAL_ACCOUNT_DECLINED":
            result = VERIFY_INTERNAL_ACCOUNT_DECLINED_AUDITAUDITRECORDTYPE
        case "VERIFY_INTERNAL_ACCOUNT_REQUESTED":
            result = VERIFY_INTERNAL_ACCOUNT_REQUESTED_AUDITAUDITRECORDTYPE
        case "WEBHOOK_CREATED":
            result = WEBHOOK_CREATED_AUDITAUDITRECORDTYPE
        case "WEBHOOK_MODIFIED":
            result = WEBHOOK_MODIFIED_AUDITAUDITRECORDTYPE
        case "WEBHOOK_REMOVED":
            result = WEBHOOK_REMOVED_AUDITAUDITRECORDTYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeAuditAuditRecordType(values []AuditAuditRecordType) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i AuditAuditRecordType) isMultiValue() bool {
    return false
}
