// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type GroupGroupMailRecipient int

const (
    MANAGERS_GROUPGROUPMAILRECIPIENT GroupGroupMailRecipient = iota
    ALL_MEMBERS_GROUPGROUPMAILRECIPIENT
)

func (i GroupGroupMailRecipient) String() string {
    return []string{"MANAGERS", "ALL_MEMBERS"}[i]
}
func ParseGroupGroupMailRecipient(v string) (any, error) {
    result := MANAGERS_GROUPGROUPMAILRECIPIENT
    switch v {
        case "MANAGERS":
            result = MANAGERS_GROUPGROUPMAILRECIPIENT
        case "ALL_MEMBERS":
            result = ALL_MEMBERS_GROUPGROUPMAILRECIPIENT
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeGroupGroupMailRecipient(values []GroupGroupMailRecipient) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i GroupGroupMailRecipient) isMultiValue() bool {
    return false
}
