// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type IdentitysourceIdentitySourceAttributeMapping struct {
    NonLinkable
    // The attribute property
    attribute IdentityAccountAttributeDefinitionable
    // The index property
    index *int32
    // The multiValued property
    multiValued *bool
}
// NewIdentitysourceIdentitySourceAttributeMapping instantiates a new IdentitysourceIdentitySourceAttributeMapping and sets the default values.
func NewIdentitysourceIdentitySourceAttributeMapping()(*IdentitysourceIdentitySourceAttributeMapping) {
    m := &IdentitysourceIdentitySourceAttributeMapping{
        NonLinkable: *NewNonLinkable(),
    }
    typeEscapedValue := "identitysource.IdentitySourceAttributeMapping"
    m.SetTypeEscaped(&typeEscapedValue)
    return m
}
// CreateIdentitysourceIdentitySourceAttributeMappingFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateIdentitysourceIdentitySourceAttributeMappingFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewIdentitysourceIdentitySourceAttributeMapping(), nil
}
// GetAttribute gets the attribute property value. The attribute property
// returns a IdentityAccountAttributeDefinitionable when successful
func (m *IdentitysourceIdentitySourceAttributeMapping) GetAttribute()(IdentityAccountAttributeDefinitionable) {
    return m.attribute
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *IdentitysourceIdentitySourceAttributeMapping) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := m.NonLinkable.GetFieldDeserializers()
    res["attribute"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateIdentityAccountAttributeDefinitionFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAttribute(val.(IdentityAccountAttributeDefinitionable))
        }
        return nil
    }
    res["index"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIndex(val)
        }
        return nil
    }
    res["multiValued"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMultiValued(val)
        }
        return nil
    }
    return res
}
// GetIndex gets the index property value. The index property
// returns a *int32 when successful
func (m *IdentitysourceIdentitySourceAttributeMapping) GetIndex()(*int32) {
    return m.index
}
// GetMultiValued gets the multiValued property value. The multiValued property
// returns a *bool when successful
func (m *IdentitysourceIdentitySourceAttributeMapping) GetMultiValued()(*bool) {
    return m.multiValued
}
// Serialize serializes information the current object
func (m *IdentitysourceIdentitySourceAttributeMapping) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    err := m.NonLinkable.Serialize(writer)
    if err != nil {
        return err
    }
    {
        err = writer.WriteObjectValue("attribute", m.GetAttribute())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteInt32Value("index", m.GetIndex())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteBoolValue("multiValued", m.GetMultiValued())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAttribute sets the attribute property value. The attribute property
func (m *IdentitysourceIdentitySourceAttributeMapping) SetAttribute(value IdentityAccountAttributeDefinitionable)() {
    m.attribute = value
}
// SetIndex sets the index property value. The index property
func (m *IdentitysourceIdentitySourceAttributeMapping) SetIndex(value *int32)() {
    m.index = value
}
// SetMultiValued sets the multiValued property value. The multiValued property
func (m *IdentitysourceIdentitySourceAttributeMapping) SetMultiValued(value *bool)() {
    m.multiValued = value
}
type IdentitysourceIdentitySourceAttributeMappingable interface {
    NonLinkableable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAttribute()(IdentityAccountAttributeDefinitionable)
    GetIndex()(*int32)
    GetMultiValued()(*bool)
    SetAttribute(value IdentityAccountAttributeDefinitionable)()
    SetIndex(value *int32)()
    SetMultiValued(value *bool)()
}
