// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type LaunchpadVaultRecordLaunchpadTile struct {
    LaunchpadLaunchpadTile
    // The vaultRecord property
    vaultRecord VaultVaultRecordPrimerable
}
// NewLaunchpadVaultRecordLaunchpadTile instantiates a new LaunchpadVaultRecordLaunchpadTile and sets the default values.
func NewLaunchpadVaultRecordLaunchpadTile()(*LaunchpadVaultRecordLaunchpadTile) {
    m := &LaunchpadVaultRecordLaunchpadTile{
        LaunchpadLaunchpadTile: *NewLaunchpadLaunchpadTile(),
    }
    typeEscapedValue := "launchpad.VaultRecordLaunchpadTile"
    m.SetTypeEscaped(&typeEscapedValue)
    return m
}
// CreateLaunchpadVaultRecordLaunchpadTileFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateLaunchpadVaultRecordLaunchpadTileFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewLaunchpadVaultRecordLaunchpadTile(), nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *LaunchpadVaultRecordLaunchpadTile) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := m.LaunchpadLaunchpadTile.GetFieldDeserializers()
    res["vaultRecord"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateVaultVaultRecordPrimerFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVaultRecord(val.(VaultVaultRecordPrimerable))
        }
        return nil
    }
    return res
}
// GetVaultRecord gets the vaultRecord property value. The vaultRecord property
// returns a VaultVaultRecordPrimerable when successful
func (m *LaunchpadVaultRecordLaunchpadTile) GetVaultRecord()(VaultVaultRecordPrimerable) {
    return m.vaultRecord
}
// Serialize serializes information the current object
func (m *LaunchpadVaultRecordLaunchpadTile) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    err := m.LaunchpadLaunchpadTile.Serialize(writer)
    if err != nil {
        return err
    }
    {
        err = writer.WriteObjectValue("vaultRecord", m.GetVaultRecord())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetVaultRecord sets the vaultRecord property value. The vaultRecord property
func (m *LaunchpadVaultRecordLaunchpadTile) SetVaultRecord(value VaultVaultRecordPrimerable)() {
    m.vaultRecord = value
}
type LaunchpadVaultRecordLaunchpadTileable interface {
    LaunchpadLaunchpadTileable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetVaultRecord()(VaultVaultRecordPrimerable)
    SetVaultRecord(value VaultVaultRecordPrimerable)()
}
