// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type LogOperationLog struct {
    Linkable
    // The context property
    context *string
    // The endTime property
    endTime *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The type property
    logOperationLogType *LogOperationType
    // The startTime property
    startTime *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The successful property
    successful *bool
}
// NewLogOperationLog instantiates a new LogOperationLog and sets the default values.
func NewLogOperationLog()(*LogOperationLog) {
    m := &LogOperationLog{
        Linkable: *NewLinkable(),
    }
    typeEscapedValue := "log.OperationLog"
    m.SetTypeEscaped(&typeEscapedValue)
    return m
}
// CreateLogOperationLogFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateLogOperationLogFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewLogOperationLog(), nil
}
// GetContext gets the context property value. The context property
// returns a *string when successful
func (m *LogOperationLog) GetContext()(*string) {
    return m.context
}
// GetEndTime gets the endTime property value. The endTime property
// returns a *Time when successful
func (m *LogOperationLog) GetEndTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.endTime
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *LogOperationLog) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := m.Linkable.GetFieldDeserializers()
    res["context"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetContext(val)
        }
        return nil
    }
    res["endTime"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEndTime(val)
        }
        return nil
    }
    res["type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseLogOperationType)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLogOperationLogType(val.(*LogOperationType))
        }
        return nil
    }
    res["startTime"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStartTime(val)
        }
        return nil
    }
    res["successful"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSuccessful(val)
        }
        return nil
    }
    return res
}
// GetLogOperationLogType gets the type property value. The type property
// returns a *LogOperationType when successful
func (m *LogOperationLog) GetLogOperationLogType()(*LogOperationType) {
    return m.logOperationLogType
}
// GetStartTime gets the startTime property value. The startTime property
// returns a *Time when successful
func (m *LogOperationLog) GetStartTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.startTime
}
// GetSuccessful gets the successful property value. The successful property
// returns a *bool when successful
func (m *LogOperationLog) GetSuccessful()(*bool) {
    return m.successful
}
// Serialize serializes information the current object
func (m *LogOperationLog) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    err := m.Linkable.Serialize(writer)
    if err != nil {
        return err
    }
    if m.GetLogOperationLogType() != nil {
        cast := (*m.GetLogOperationLogType()).String()
        err = writer.WriteStringValue("type", &cast)
        if err != nil {
            return err
        }
    }
    return nil
}
// SetContext sets the context property value. The context property
func (m *LogOperationLog) SetContext(value *string)() {
    m.context = value
}
// SetEndTime sets the endTime property value. The endTime property
func (m *LogOperationLog) SetEndTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.endTime = value
}
// SetLogOperationLogType sets the type property value. The type property
func (m *LogOperationLog) SetLogOperationLogType(value *LogOperationType)() {
    m.logOperationLogType = value
}
// SetStartTime sets the startTime property value. The startTime property
func (m *LogOperationLog) SetStartTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.startTime = value
}
// SetSuccessful sets the successful property value. The successful property
func (m *LogOperationLog) SetSuccessful(value *bool)() {
    m.successful = value
}
type LogOperationLogable interface {
    Linkableable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetContext()(*string)
    GetEndTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetLogOperationLogType()(*LogOperationType)
    GetStartTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetSuccessful()(*bool)
    SetContext(value *string)()
    SetEndTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetLogOperationLogType(value *LogOperationType)()
    SetStartTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetSuccessful(value *bool)()
}
