// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type MiscAttributeCustomization struct {
    NonLinkable
    // The attributeDefinition property
    attributeDefinition IdentityAccountAttributeDefinitionable
    // The name property
    name *string
    // The script property
    script *string
}
// NewMiscAttributeCustomization instantiates a new MiscAttributeCustomization and sets the default values.
func NewMiscAttributeCustomization()(*MiscAttributeCustomization) {
    m := &MiscAttributeCustomization{
        NonLinkable: *NewNonLinkable(),
    }
    typeEscapedValue := "misc.AttributeCustomization"
    m.SetTypeEscaped(&typeEscapedValue)
    return m
}
// CreateMiscAttributeCustomizationFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateMiscAttributeCustomizationFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewMiscAttributeCustomization(), nil
}
// GetAttributeDefinition gets the attributeDefinition property value. The attributeDefinition property
// returns a IdentityAccountAttributeDefinitionable when successful
func (m *MiscAttributeCustomization) GetAttributeDefinition()(IdentityAccountAttributeDefinitionable) {
    return m.attributeDefinition
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *MiscAttributeCustomization) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := m.NonLinkable.GetFieldDeserializers()
    res["attributeDefinition"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateIdentityAccountAttributeDefinitionFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAttributeDefinition(val.(IdentityAccountAttributeDefinitionable))
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["script"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetScript(val)
        }
        return nil
    }
    return res
}
// GetName gets the name property value. The name property
// returns a *string when successful
func (m *MiscAttributeCustomization) GetName()(*string) {
    return m.name
}
// GetScript gets the script property value. The script property
// returns a *string when successful
func (m *MiscAttributeCustomization) GetScript()(*string) {
    return m.script
}
// Serialize serializes information the current object
func (m *MiscAttributeCustomization) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    err := m.NonLinkable.Serialize(writer)
    if err != nil {
        return err
    }
    {
        err = writer.WriteObjectValue("attributeDefinition", m.GetAttributeDefinition())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("script", m.GetScript())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAttributeDefinition sets the attributeDefinition property value. The attributeDefinition property
func (m *MiscAttributeCustomization) SetAttributeDefinition(value IdentityAccountAttributeDefinitionable)() {
    m.attributeDefinition = value
}
// SetName sets the name property value. The name property
func (m *MiscAttributeCustomization) SetName(value *string)() {
    m.name = value
}
// SetScript sets the script property value. The script property
func (m *MiscAttributeCustomization) SetScript(value *string)() {
    m.script = value
}
type MiscAttributeCustomizationable interface {
    NonLinkableable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAttributeDefinition()(IdentityAccountAttributeDefinitionable)
    GetName()(*string)
    GetScript()(*string)
    SetAttributeDefinition(value IdentityAccountAttributeDefinitionable)()
    SetName(value *string)()
    SetScript(value *string)()
}
