// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type ProvisioningProvisioningOperationAction int

const (
    LOG_PROVISIONINGPROVISIONINGOPERATIONACTION ProvisioningProvisioningOperationAction = iota
    READ_PROVISIONINGPROVISIONINGOPERATIONACTION
    WRITE_PROVISIONINGPROVISIONINGOPERATIONACTION
)

func (i ProvisioningProvisioningOperationAction) String() string {
    return []string{"LOG", "READ", "WRITE"}[i]
}
func ParseProvisioningProvisioningOperationAction(v string) (any, error) {
    result := LOG_PROVISIONINGPROVISIONINGOPERATIONACTION
    switch v {
        case "LOG":
            result = LOG_PROVISIONINGPROVISIONINGOPERATIONACTION
        case "READ":
            result = READ_PROVISIONINGPROVISIONINGOPERATIONACTION
        case "WRITE":
            result = WRITE_PROVISIONINGPROVISIONINGOPERATIONACTION
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeProvisioningProvisioningOperationAction(values []ProvisioningProvisioningOperationAction) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i ProvisioningProvisioningOperationAction) isMultiValue() bool {
    return false
}
