// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ProvisioningProvisioningOperationLogLine struct {
    Linkable
    // The accessProfile property
    accessProfile *string
    // The account property
    account *string
    // The action property
    action *ProvisioningProvisioningOperationAction
    // The group property
    group *string
    // The groupOnSystem property
    groupOnSystem *string
    // The level property
    level *ProvisioningProvisioningOperationLogLevel
    // The message property
    message *string
    // The serviceAccount property
    serviceAccount *string
    // The system property
    system *string
    // The thread property
    thread *string
    // The time property
    time *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
}
// NewProvisioningProvisioningOperationLogLine instantiates a new ProvisioningProvisioningOperationLogLine and sets the default values.
func NewProvisioningProvisioningOperationLogLine()(*ProvisioningProvisioningOperationLogLine) {
    m := &ProvisioningProvisioningOperationLogLine{
        Linkable: *NewLinkable(),
    }
    typeEscapedValue := "provisioning.ProvisioningOperationLogLine"
    m.SetTypeEscaped(&typeEscapedValue)
    return m
}
// CreateProvisioningProvisioningOperationLogLineFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateProvisioningProvisioningOperationLogLineFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewProvisioningProvisioningOperationLogLine(), nil
}
// GetAccessProfile gets the accessProfile property value. The accessProfile property
// returns a *string when successful
func (m *ProvisioningProvisioningOperationLogLine) GetAccessProfile()(*string) {
    return m.accessProfile
}
// GetAccount gets the account property value. The account property
// returns a *string when successful
func (m *ProvisioningProvisioningOperationLogLine) GetAccount()(*string) {
    return m.account
}
// GetAction gets the action property value. The action property
// returns a *ProvisioningProvisioningOperationAction when successful
func (m *ProvisioningProvisioningOperationLogLine) GetAction()(*ProvisioningProvisioningOperationAction) {
    return m.action
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ProvisioningProvisioningOperationLogLine) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := m.Linkable.GetFieldDeserializers()
    res["accessProfile"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAccessProfile(val)
        }
        return nil
    }
    res["account"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAccount(val)
        }
        return nil
    }
    res["action"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseProvisioningProvisioningOperationAction)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAction(val.(*ProvisioningProvisioningOperationAction))
        }
        return nil
    }
    res["group"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetGroup(val)
        }
        return nil
    }
    res["groupOnSystem"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetGroupOnSystem(val)
        }
        return nil
    }
    res["level"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseProvisioningProvisioningOperationLogLevel)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLevel(val.(*ProvisioningProvisioningOperationLogLevel))
        }
        return nil
    }
    res["message"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMessage(val)
        }
        return nil
    }
    res["serviceAccount"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetServiceAccount(val)
        }
        return nil
    }
    res["system"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSystem(val)
        }
        return nil
    }
    res["thread"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetThread(val)
        }
        return nil
    }
    res["time"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTime(val)
        }
        return nil
    }
    return res
}
// GetGroup gets the group property value. The group property
// returns a *string when successful
func (m *ProvisioningProvisioningOperationLogLine) GetGroup()(*string) {
    return m.group
}
// GetGroupOnSystem gets the groupOnSystem property value. The groupOnSystem property
// returns a *string when successful
func (m *ProvisioningProvisioningOperationLogLine) GetGroupOnSystem()(*string) {
    return m.groupOnSystem
}
// GetLevel gets the level property value. The level property
// returns a *ProvisioningProvisioningOperationLogLevel when successful
func (m *ProvisioningProvisioningOperationLogLine) GetLevel()(*ProvisioningProvisioningOperationLogLevel) {
    return m.level
}
// GetMessage gets the message property value. The message property
// returns a *string when successful
func (m *ProvisioningProvisioningOperationLogLine) GetMessage()(*string) {
    return m.message
}
// GetServiceAccount gets the serviceAccount property value. The serviceAccount property
// returns a *string when successful
func (m *ProvisioningProvisioningOperationLogLine) GetServiceAccount()(*string) {
    return m.serviceAccount
}
// GetSystem gets the system property value. The system property
// returns a *string when successful
func (m *ProvisioningProvisioningOperationLogLine) GetSystem()(*string) {
    return m.system
}
// GetThread gets the thread property value. The thread property
// returns a *string when successful
func (m *ProvisioningProvisioningOperationLogLine) GetThread()(*string) {
    return m.thread
}
// GetTime gets the time property value. The time property
// returns a *Time when successful
func (m *ProvisioningProvisioningOperationLogLine) GetTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.time
}
// Serialize serializes information the current object
func (m *ProvisioningProvisioningOperationLogLine) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    err := m.Linkable.Serialize(writer)
    if err != nil {
        return err
    }
    if m.GetAction() != nil {
        cast := (*m.GetAction()).String()
        err = writer.WriteStringValue("action", &cast)
        if err != nil {
            return err
        }
    }
    if m.GetLevel() != nil {
        cast := (*m.GetLevel()).String()
        err = writer.WriteStringValue("level", &cast)
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAccessProfile sets the accessProfile property value. The accessProfile property
func (m *ProvisioningProvisioningOperationLogLine) SetAccessProfile(value *string)() {
    m.accessProfile = value
}
// SetAccount sets the account property value. The account property
func (m *ProvisioningProvisioningOperationLogLine) SetAccount(value *string)() {
    m.account = value
}
// SetAction sets the action property value. The action property
func (m *ProvisioningProvisioningOperationLogLine) SetAction(value *ProvisioningProvisioningOperationAction)() {
    m.action = value
}
// SetGroup sets the group property value. The group property
func (m *ProvisioningProvisioningOperationLogLine) SetGroup(value *string)() {
    m.group = value
}
// SetGroupOnSystem sets the groupOnSystem property value. The groupOnSystem property
func (m *ProvisioningProvisioningOperationLogLine) SetGroupOnSystem(value *string)() {
    m.groupOnSystem = value
}
// SetLevel sets the level property value. The level property
func (m *ProvisioningProvisioningOperationLogLine) SetLevel(value *ProvisioningProvisioningOperationLogLevel)() {
    m.level = value
}
// SetMessage sets the message property value. The message property
func (m *ProvisioningProvisioningOperationLogLine) SetMessage(value *string)() {
    m.message = value
}
// SetServiceAccount sets the serviceAccount property value. The serviceAccount property
func (m *ProvisioningProvisioningOperationLogLine) SetServiceAccount(value *string)() {
    m.serviceAccount = value
}
// SetSystem sets the system property value. The system property
func (m *ProvisioningProvisioningOperationLogLine) SetSystem(value *string)() {
    m.system = value
}
// SetThread sets the thread property value. The thread property
func (m *ProvisioningProvisioningOperationLogLine) SetThread(value *string)() {
    m.thread = value
}
// SetTime sets the time property value. The time property
func (m *ProvisioningProvisioningOperationLogLine) SetTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.time = value
}
type ProvisioningProvisioningOperationLogLineable interface {
    Linkableable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAccessProfile()(*string)
    GetAccount()(*string)
    GetAction()(*ProvisioningProvisioningOperationAction)
    GetGroup()(*string)
    GetGroupOnSystem()(*string)
    GetLevel()(*ProvisioningProvisioningOperationLogLevel)
    GetMessage()(*string)
    GetServiceAccount()(*string)
    GetSystem()(*string)
    GetThread()(*string)
    GetTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    SetAccessProfile(value *string)()
    SetAccount(value *string)()
    SetAction(value *ProvisioningProvisioningOperationAction)()
    SetGroup(value *string)()
    SetGroupOnSystem(value *string)()
    SetLevel(value *ProvisioningProvisioningOperationLogLevel)()
    SetMessage(value *string)()
    SetServiceAccount(value *string)()
    SetSystem(value *string)()
    SetThread(value *string)()
    SetTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
}
