package models
type RequestModificationRequestReportChange int

const (
    ACCOUNT_REMOVED_FROM_GROUP_REQUESTMODIFICATIONREQUESTREPORTCHANGE RequestModificationRequestReportChange = iota
    MODIFICATION_REQUEST_CANCELLED_REQUESTMODIFICATIONREQUESTREPORTCHANGE
    PROVISIONING_GROUP_REMOVED_OUT_OF_SCOPE_REQUESTMODIFICATIONREQUESTREPORTCHANGE
    PROVISIONING_GROUP_REMOVED_OWNER_REQUESTMODIFICATIONREQUESTREPORTCHANGE
    SERVICE_ACCOUNT_GROUP_REMOVED_OUT_OF_SCOPE_REQUESTMODIFICATIONREQUESTREPORTCHANGE
    SERVICE_ACCOUNT_GROUP_REMOVED_OWNER_REQUESTMODIFICATIONREQUESTREPORTCHANGE
)

func (i RequestModificationRequestReportChange) String() string {
    return []string{"ACCOUNT_REMOVED_FROM_GROUP", "MODIFICATION_REQUEST_CANCELLED", "PROVISIONING_GROUP_REMOVED_OUT_OF_SCOPE", "PROVISIONING_GROUP_REMOVED_OWNER", "SERVICE_ACCOUNT_GROUP_REMOVED_OUT_OF_SCOPE", "SERVICE_ACCOUNT_GROUP_REMOVED_OWNER"}[i]
}
func ParseRequestModificationRequestReportChange(v string) (any, error) {
    result := ACCOUNT_REMOVED_FROM_GROUP_REQUESTMODIFICATIONREQUESTREPORTCHANGE
    switch v {
        case "ACCOUNT_REMOVED_FROM_GROUP":
            result = ACCOUNT_REMOVED_FROM_GROUP_REQUESTMODIFICATIONREQUESTREPORTCHANGE
        case "MODIFICATION_REQUEST_CANCELLED":
            result = MODIFICATION_REQUEST_CANCELLED_REQUESTMODIFICATIONREQUESTREPORTCHANGE
        case "PROVISIONING_GROUP_REMOVED_OUT_OF_SCOPE":
            result = PROVISIONING_GROUP_REMOVED_OUT_OF_SCOPE_REQUESTMODIFICATIONREQUESTREPORTCHANGE
        case "PROVISIONING_GROUP_REMOVED_OWNER":
            result = PROVISIONING_GROUP_REMOVED_OWNER_REQUESTMODIFICATIONREQUESTREPORTCHANGE
        case "SERVICE_ACCOUNT_GROUP_REMOVED_OUT_OF_SCOPE":
            result = SERVICE_ACCOUNT_GROUP_REMOVED_OUT_OF_SCOPE_REQUESTMODIFICATIONREQUESTREPORTCHANGE
        case "SERVICE_ACCOUNT_GROUP_REMOVED_OWNER":
            result = SERVICE_ACCOUNT_GROUP_REMOVED_OWNER_REQUESTMODIFICATIONREQUESTREPORTCHANGE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeRequestModificationRequestReportChange(values []RequestModificationRequestReportChange) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i RequestModificationRequestReportChange) isMultiValue() bool {
    return false
}
