package models
import (
    "errors"
)
// 
type RequestModificationRequestType int

const (
    ADD_GROUP_ADMIN_REQUESTMODIFICATIONREQUESTTYPE RequestModificationRequestType = iota
    CREATE_GROUP_REQUESTMODIFICATIONREQUESTTYPE
    CREATE_GROUP_ON_SYSTEM_REQUESTMODIFICATIONREQUESTTYPE
    CREATE_PROVISIONED_NAMESPACE_REQUESTMODIFICATIONREQUESTTYPE
    CREATE_SERVICE_ACCOUNT_REQUESTMODIFICATIONREQUESTTYPE
    DISABLE_2FA_REQUESTMODIFICATIONREQUESTTYPE
    ENABLE_TECHNICAL_ADMINISTRATION_REQUESTMODIFICATIONREQUESTTYPE
    EXTEND_ACCESS_REQUESTMODIFICATIONREQUESTTYPE
    GRANT_ACCESS_REQUESTMODIFICATIONREQUESTTYPE
    GRANT_APPLICATION_REQUESTMODIFICATIONREQUESTTYPE
    GRANT_CLIENT_PERMISSION_REQUESTMODIFICATIONREQUESTTYPE
    GRANT_GROUP_ON_SYSTEM_REQUESTMODIFICATIONREQUESTTYPE
    GRANT_GROUP_ON_SYSTEM_REQUEST_REQUESTMODIFICATIONREQUESTTYPE
    GRANT_SERVICE_ACCOUNT_GROUP_REQUESTMODIFICATIONREQUESTTYPE
    JOIN_GROUP_REQUESTMODIFICATIONREQUESTTYPE
    JOIN_VAULT_REQUESTMODIFICATIONREQUESTTYPE
    REMOVE_GROUP_REQUESTMODIFICATIONREQUESTTYPE
    REMOVE_ORGANIZATIONAL_UNIT_REQUESTMODIFICATIONREQUESTTYPE
    REMOVE_PROVISIONED_SYSTEM_REQUESTMODIFICATIONREQUESTTYPE
    RESET_PASSWORD_REQUESTMODIFICATIONREQUESTTYPE
    REVIEW_AUDIT_REQUESTMODIFICATIONREQUESTTYPE
    REVOKE_ADMIN_REQUESTMODIFICATIONREQUESTTYPE
    SETUP_AUTHORIZING_GROUP_REQUESTMODIFICATIONREQUESTTYPE
    SETUP_NESTED_GROUP_REQUESTMODIFICATIONREQUESTTYPE
    TRANSFER_APPLICATION_ADMINISTRATION_REQUESTMODIFICATIONREQUESTTYPE
    TRANSFER_APPLICATION_OWNERSHIP_REQUESTMODIFICATIONREQUESTTYPE
    TRANSFER_AUDITOR_GROUP_REQUESTMODIFICATIONREQUESTTYPE
    TRANSFER_GROUP_ON_SYSTEM_OWNERSHIP_REQUESTMODIFICATIONREQUESTTYPE
    TRANSFER_ORGANIZATIONAL_UNIT_OWNERSHIP_REQUESTMODIFICATIONREQUESTTYPE
    TRANSFER_PROVISIONED_SYSTEM_ADMINISTRATION_REQUESTMODIFICATIONREQUESTTYPE
    TRANSFER_PROVISIONED_SYSTEM_CONTENT_ADMINISTRATION_REQUESTMODIFICATIONREQUESTTYPE
    TRANSFER_PROVISIONED_SYSTEM_OWNERSHIP_REQUESTMODIFICATIONREQUESTTYPE
    TRANSFER_SERVICE_ACCOUNT_ADMINISTRATION_REQUESTMODIFICATIONREQUESTTYPE
    UPDATE_GROUP_MEMBERSHIP_REQUESTMODIFICATIONREQUESTTYPE
    VERIFY_INTERNAL_ACCOUNT_REQUESTMODIFICATIONREQUESTTYPE
)

func (i RequestModificationRequestType) String() string {
    return []string{"ADD_GROUP_ADMIN", "CREATE_GROUP", "CREATE_GROUP_ON_SYSTEM", "CREATE_PROVISIONED_NAMESPACE", "CREATE_SERVICE_ACCOUNT", "DISABLE_2FA", "ENABLE_TECHNICAL_ADMINISTRATION", "EXTEND_ACCESS", "GRANT_ACCESS", "GRANT_APPLICATION", "GRANT_CLIENT_PERMISSION", "GRANT_GROUP_ON_SYSTEM", "GRANT_GROUP_ON_SYSTEM_REQUEST", "GRANT_SERVICE_ACCOUNT_GROUP", "JOIN_GROUP", "JOIN_VAULT", "REMOVE_GROUP", "REMOVE_ORGANIZATIONAL_UNIT", "REMOVE_PROVISIONED_SYSTEM", "RESET_PASSWORD", "REVIEW_AUDIT", "REVOKE_ADMIN", "SETUP_AUTHORIZING_GROUP", "SETUP_NESTED_GROUP", "TRANSFER_APPLICATION_ADMINISTRATION", "TRANSFER_APPLICATION_OWNERSHIP", "TRANSFER_AUDITOR_GROUP", "TRANSFER_GROUP_ON_SYSTEM_OWNERSHIP", "TRANSFER_ORGANIZATIONAL_UNIT_OWNERSHIP", "TRANSFER_PROVISIONED_SYSTEM_ADMINISTRATION", "TRANSFER_PROVISIONED_SYSTEM_CONTENT_ADMINISTRATION", "TRANSFER_PROVISIONED_SYSTEM_OWNERSHIP", "TRANSFER_SERVICE_ACCOUNT_ADMINISTRATION", "UPDATE_GROUP_MEMBERSHIP", "VERIFY_INTERNAL_ACCOUNT"}[i]
}
func ParseRequestModificationRequestType(v string) (any, error) {
    result := ADD_GROUP_ADMIN_REQUESTMODIFICATIONREQUESTTYPE
    switch v {
        case "ADD_GROUP_ADMIN":
            result = ADD_GROUP_ADMIN_REQUESTMODIFICATIONREQUESTTYPE
        case "CREATE_GROUP":
            result = CREATE_GROUP_REQUESTMODIFICATIONREQUESTTYPE
        case "CREATE_GROUP_ON_SYSTEM":
            result = CREATE_GROUP_ON_SYSTEM_REQUESTMODIFICATIONREQUESTTYPE
        case "CREATE_PROVISIONED_NAMESPACE":
            result = CREATE_PROVISIONED_NAMESPACE_REQUESTMODIFICATIONREQUESTTYPE
        case "CREATE_SERVICE_ACCOUNT":
            result = CREATE_SERVICE_ACCOUNT_REQUESTMODIFICATIONREQUESTTYPE
        case "DISABLE_2FA":
            result = DISABLE_2FA_REQUESTMODIFICATIONREQUESTTYPE
        case "ENABLE_TECHNICAL_ADMINISTRATION":
            result = ENABLE_TECHNICAL_ADMINISTRATION_REQUESTMODIFICATIONREQUESTTYPE
        case "EXTEND_ACCESS":
            result = EXTEND_ACCESS_REQUESTMODIFICATIONREQUESTTYPE
        case "GRANT_ACCESS":
            result = GRANT_ACCESS_REQUESTMODIFICATIONREQUESTTYPE
        case "GRANT_APPLICATION":
            result = GRANT_APPLICATION_REQUESTMODIFICATIONREQUESTTYPE
        case "GRANT_CLIENT_PERMISSION":
            result = GRANT_CLIENT_PERMISSION_REQUESTMODIFICATIONREQUESTTYPE
        case "GRANT_GROUP_ON_SYSTEM":
            result = GRANT_GROUP_ON_SYSTEM_REQUESTMODIFICATIONREQUESTTYPE
        case "GRANT_GROUP_ON_SYSTEM_REQUEST":
            result = GRANT_GROUP_ON_SYSTEM_REQUEST_REQUESTMODIFICATIONREQUESTTYPE
        case "GRANT_SERVICE_ACCOUNT_GROUP":
            result = GRANT_SERVICE_ACCOUNT_GROUP_REQUESTMODIFICATIONREQUESTTYPE
        case "JOIN_GROUP":
            result = JOIN_GROUP_REQUESTMODIFICATIONREQUESTTYPE
        case "JOIN_VAULT":
            result = JOIN_VAULT_REQUESTMODIFICATIONREQUESTTYPE
        case "REMOVE_GROUP":
            result = REMOVE_GROUP_REQUESTMODIFICATIONREQUESTTYPE
        case "REMOVE_ORGANIZATIONAL_UNIT":
            result = REMOVE_ORGANIZATIONAL_UNIT_REQUESTMODIFICATIONREQUESTTYPE
        case "REMOVE_PROVISIONED_SYSTEM":
            result = REMOVE_PROVISIONED_SYSTEM_REQUESTMODIFICATIONREQUESTTYPE
        case "RESET_PASSWORD":
            result = RESET_PASSWORD_REQUESTMODIFICATIONREQUESTTYPE
        case "REVIEW_AUDIT":
            result = REVIEW_AUDIT_REQUESTMODIFICATIONREQUESTTYPE
        case "REVOKE_ADMIN":
            result = REVOKE_ADMIN_REQUESTMODIFICATIONREQUESTTYPE
        case "SETUP_AUTHORIZING_GROUP":
            result = SETUP_AUTHORIZING_GROUP_REQUESTMODIFICATIONREQUESTTYPE
        case "SETUP_NESTED_GROUP":
            result = SETUP_NESTED_GROUP_REQUESTMODIFICATIONREQUESTTYPE
        case "TRANSFER_APPLICATION_ADMINISTRATION":
            result = TRANSFER_APPLICATION_ADMINISTRATION_REQUESTMODIFICATIONREQUESTTYPE
        case "TRANSFER_APPLICATION_OWNERSHIP":
            result = TRANSFER_APPLICATION_OWNERSHIP_REQUESTMODIFICATIONREQUESTTYPE
        case "TRANSFER_AUDITOR_GROUP":
            result = TRANSFER_AUDITOR_GROUP_REQUESTMODIFICATIONREQUESTTYPE
        case "TRANSFER_GROUP_ON_SYSTEM_OWNERSHIP":
            result = TRANSFER_GROUP_ON_SYSTEM_OWNERSHIP_REQUESTMODIFICATIONREQUESTTYPE
        case "TRANSFER_ORGANIZATIONAL_UNIT_OWNERSHIP":
            result = TRANSFER_ORGANIZATIONAL_UNIT_OWNERSHIP_REQUESTMODIFICATIONREQUESTTYPE
        case "TRANSFER_PROVISIONED_SYSTEM_ADMINISTRATION":
            result = TRANSFER_PROVISIONED_SYSTEM_ADMINISTRATION_REQUESTMODIFICATIONREQUESTTYPE
        case "TRANSFER_PROVISIONED_SYSTEM_CONTENT_ADMINISTRATION":
            result = TRANSFER_PROVISIONED_SYSTEM_CONTENT_ADMINISTRATION_REQUESTMODIFICATIONREQUESTTYPE
        case "TRANSFER_PROVISIONED_SYSTEM_OWNERSHIP":
            result = TRANSFER_PROVISIONED_SYSTEM_OWNERSHIP_REQUESTMODIFICATIONREQUESTTYPE
        case "TRANSFER_SERVICE_ACCOUNT_ADMINISTRATION":
            result = TRANSFER_SERVICE_ACCOUNT_ADMINISTRATION_REQUESTMODIFICATIONREQUESTTYPE
        case "UPDATE_GROUP_MEMBERSHIP":
            result = UPDATE_GROUP_MEMBERSHIP_REQUESTMODIFICATIONREQUESTTYPE
        case "VERIFY_INTERNAL_ACCOUNT":
            result = VERIFY_INTERNAL_ACCOUNT_REQUESTMODIFICATIONREQUESTTYPE
        default:
            return 0, errors.New("Unknown RequestModificationRequestType value: " + v)
    }
    return &result, nil
}
func SerializeRequestModificationRequestType(values []RequestModificationRequestType) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i RequestModificationRequestType) isMultiValue() bool {
    return false
}
